tests/Makefile.am, tests/harness/Makefile.am
Previously the test would fail or possibly succeed in some rare
cases, but using old binaries.
FYI: ./autogen.sh && mkdir build && cd build && ../configure --enable-ucs4 && make && make check && make distcheck && echo 'Success!' => Success!
=> Fixed tests for subdir-build.

Makefile.am, NEWS, configure.ac
If we cannot find makeinfo 5 simply do not build the documentation
=> Make dependency on makeinfo 5 optional

doc/liblouis.texi, python/louis/__init__.py.in
The Python function is called `compile` to clearly indicate that it is not entirely the same as `lou_getTable`. Specifically, the Python version doesn't return a value, but it it does throw an exception when an error occurs.
TODO: Maybe add all remaining missing functions to the Python bindings?
=> Add lou_getTable to the Python bindings

liblouis/Makefile.am, liblouis/compileTranslationTable.c, liblouis/findTable.c, liblouis/findTable.h, liblouis/louis.h
which is not exported and not visible in liblouisutdml. This should
avoid problems in liblouisutdml and should fix #92.
=> Move internal definitions for findtable in a separate header file

configure.ac
makeinfo, which is nowadays provided by texi2any, reports texi2any as
of version 6.0.
=> Update configure.ac to reconize texi2any

tests/harness/runHarness.py
According to the documentation of json.load the encoding argument is ignored and deprecated: https://docs.python.org/3/library/json.html
I noticed the problem on a Windows machine.
Please check if this change doesn't break things on other platforms.
=> runHarness.py: fix decoding of JSON files

liblouis/compileTranslationTable.c, liblouis/lou_translateString.c, liblouis/louis.h
Solves issue #126. Tested with the Danish tables that use hyphenation extensively, so should Work.
=> untangled and removed nobreak from code

liblouis/compileTranslationTable.c, liblouis/liblouis.h.in, liblouis/logging.c, liblouis/lou_translateString.c, windows/Makefile.nmake, windows/include/liblouis.h
Solves issue #127. Fixed all warnings up to and including warning level 3. Still quite a few warnings on level 4, but they can probably be ignored. Warning level raised to 3 in makefile.nmake, so that future code modifications can be checked more closely.
=> Fix vs warnings

tests/yaml/fi_harness.yaml
Add more tests for cases where only a part of a word is emphasized.
=> Add tests for emphasis edge cases

windows/liblouis.def
These seem to be missing from the windows def file which was stopping windows building liblouis dll
=> add new Beta APIs

tables/hu-backtranslate-correction.dis, tables/hu-chardefs.cti, tables/hu-exceptionwords.cti, tables/hu-hu-comp8.ctb, tables/hu-hu-g1.ctb
Hi Chris,
Based an another pull request consultation for you, I completed hungarian braille tables  the copyright header with following form:
Attila Hammer from IT Foundation for the Visually Impaired - Hungary.
I increased the second year column in copyright header with 2016,  except the hu-hu-comp8.ctb table, because this table doesn't happened modifications since 2012.
Please review this change, and if all looks good your openion, please merge this pull request into Liblouis proper branches.
If I need doing next years any modifications with hungarian braille tables and the included files (for example the hu-exceptionwords.cti included file), I will updating the second year column the actual year when the modification is happened.
Sorry to previous forgot this since 2014.
Attila
=> Hungarian braille tables: completed and actualized the year column in copyright header

tests/Makefile.am, tools/Makefile.am, tools/brl_checks.c, tools/lou_allround.c, tools/lou_debug.c, tools/lou_translate.c
All the tools should now be able to emit utf8. The home-made (aka copied
from stackoverflow) code to comvert to utf8 in brl_checks.c has also
been replaced with u32_to_u8 and u16_to_u8 from unistr.h
=> Use gnulibs unistr.h to convert ucs to utf8 in the tools

doc/liblouis.texi, liblouis/compileTranslationTable.c, liblouis/liblouis.h.in, liblouis/lou_backTranslateString.c, liblouis/lou_translateString.c, liblouis/louis.h, python/louis/__init__.py.in, tests/checkTable.c, tools/lou_allround.c, tools/lou_checkhyphens.c, tools/lou_checktable.c, tools/lou_debug.c, tools/lou_trace.c, windows/include/liblouis.h, windows/liblouis.def
Follow-up of liblouis/liblouis#89.
* Turn `lou_getTable` into a simple wrapper for `getTable`.
* Use `getTable` instead of `lou_getTable` in internal code where possible.
* Add `lou_checkTable` based on the Python implementation.
* In Python, simply call the C function.
* Update docs and tests.
=> Move lou_checkTable() to the C API

doc/liblouis.texi, liblouis/compileTranslationTable.c, liblouis/liblouis.h.in, python/louis/__init__.py.in, tests/Makefile.am, tests/tables/emphclass/emphclass_valid.utb, tests/typeform_for_emphclass.c, windows/include/liblouis.h, windows/liblouis.def
For example to find out if tables define commonly used class names such as transnote, prodnote, strikethrough, superscript, etc.
=> Add function lou_getTypeformForEmphClass

liblouis/louis.h
I am cross-compiling liblouis using clang to create javascript bindings for liblouis. While GCC only complains about the forward declaration, clang refuses to compile the code. This pull request adds "pattern_check" to the internal header file "louis.h".
---
Error messages for reference:
__CLANG/LLVM:__
```
lou_backTranslateString.c:809:10: error: implicit declaration of function 'pattern_check' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
if(!pattern_check(currentInput, src - 1, -1, -1, pattern, table))
```
__GCC:__
```
lou_backTranslateString.c:809:6: warning: implicit declaration of function ‘pattern_check’ [-Wimplicit-function-declaration]
if(!pattern_check(currentInput, src - 1, -1, -1, pattern, table))
```
=> implicit declaration of function 'pattern_check'

README.windows, windows/liblouis.def
This commit removes 2 beta api symbols from the module definition file
(windows/liblouis.def) and allows liblouis to be built on windows by
using nmake.
Liblouis wasn't built on windows due to 2 unresolved external symbol
errors. These errors were caused by having a reference to beta-api
functions defined on findTable.c (lou_indexTables and lou_findTable),
which still have some platform-specific dependencies (dirent.h,
strndup.c).
The object file for findTable was already not being built on
Makefile.nmake, so this change simply makes it able to link against only
the supported objects and successfully produce liblouis binaries on
windows (liblouis.dll, liblouis.lib, liblouis.exp).
=> Fix unresolved external symbol errors when building on windows

.gitignore, doc/liblouis.texi, liblouis/liblouis.h.in, liblouis/lou_backTranslateString.c, python/louis/__init__.py.in, tests/Makefile.am, tests/backtranslate_noUndefinedDots.c, tests/backtranslate_partialTrans.c, tools/lou_checkyaml.c
1. Add a noUndefinedDots mode to disable the output of dot numbers when back-translating undefined patterns.
When backtranslating input from a braille keyboard cell by cell, it is desirable to output characters as soon as they are produced. Similarly, when backtranslating contracted braille, it is desirable to provide a "guess" to the user of the characters they typed. To achieve this, liblouis needs to have the ability to produce no text when indicators (which don't produce a character by themselves) are not followed by another cell. This works already for indicators liblouis knows about such as capital sign, number sign, etc., but it does not work for indicators which are not (and cannot be) specifically defined as indicators. For example, in UEB, dots 4 5 6 alone produces the text …
=> Add noUndefinedDots and partialTrans modes for back-translation of input being typed on a braille keyboard

liblouis/compileTranslationTable.c
This change moves the memory allocation for the patterns variable from
the stack to the heap inside the compileRule function. The patterns
variable was a widechar array with size 27720 which usually takes 54KB
of memory (or 108KB if UCS=4). When there's not available memory on the
stack this could lead to stackoverflow crashes or accessing unmapped
memory. As this variable is declared in 2 places (with different scopes)
inside the function, an executable could require at least 108KB (or
216KB if USC=4) of stack memory per compileRule call.
Similarly to other places, it also adds a check which calls outOfMemory
in case of not having sufficient available memory on the heap.
The fix is especially important if we consider that some applications
might have smaller stack size limits and …
=> Fix for stackoverflow crashes on applications with smaller stack size

tables/unicode-braille.utb
As proposed in #214, added a new unicode braille table based on braille-patterns.cti. This adds the possibility to back translate braille input to unicode braille output. Implements #214
=> Unicode braille table for back translating to unicode braille output #214

liblouis/compileTranslationTable.c
It points to [U+0016](http://www.fileformat.info/info/unicode/char/0016/index.htm) but the manual suggests it should be [U+000B](http://www.fileformat.info/info/unicode/char/000b/index.htm).
=> Fix the \v escape character

tools/lou_checkyaml.c
Show an error, rather than crash, if the file can't be opened.
Include <unistd.h> for chdir().
=> lou_checkyaml.c fixes: (dm)

tables/Makefile.am, tables/en-us-comp8-ext.utb, tables/en_US-comp8-ext.tbl, tests/Makefile.am, tests/yaml/Makefile.am, tests/yaml/en-us-comp8-ext-back_harness.yaml, tests/yaml/en-us-comp8-ext-for_harness.yaml
This table solves the problem that the `en-us-comp8` table only covers the ASCII characters. It is based on the most popular screen readers for Windows. While it takes inspiration from these screen readers, the intend is not to copy a single product. Rather, I tried to create a table that is familiar to Windows users.
As mentioned above there isn't really an official standard. The table file documents the design decisions and describes what other tables do. Any and all feedback is much appreciated.
From that table file:
Goals
* Complete coverage of the characters in [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252).
* Definitions for other common symbols.
* Unambiguous backtranslation.
* Easy to adopt by users of Windows screen readers.
=> Add an extended 8-dot computer braille table for U.S. English

liblouis/compileTranslationTable.c, liblouis/liblouis.h.in, liblouis/louis.h, tests/emphclass.c, tools/lou_checkyaml.c
This allows it to be called by user applications.
It now points directly to the class names because const has been added
to protect them.
=> Move getEmphClasses() to liblouis.h (from louis.h).

.gitignore, tests/Makefile.am
Added infiniteTranslationLoop to noinst_PROGRAMS in tests/Makefile.am
=> Silence the infiniteTranslationLoop build warning.

tables/Makefile.am, tables/fr-fr-g1.utb, tables/litdigits6DotsPlusDot6.uti, tables/vi-g1.ctb, tests/yaml/fr-fr-g1_backward.yaml, tests/yaml/fr-fr-g1_harness.yaml, tests/yaml/vi-g1_backward.yaml, tests/yaml/vi-g1_harness.yaml
This commit adds the litdigit definition for the french and vietnamese
grade 1 tables. These tables only included the digit definition from
digits6DotsPlusDot6.uti, which would provide the correct translations only for computer braille.
Previously, back-translations for a set of cells starting with the number sign
would behave differently from the forward translations, returning
space for 0 (3456-3456) or ignoring the number sign for other digits (e.g. a with
circumflex for 3456-16 instead of 1).
=> Fix for number back-translations on fr-fr-g1 and vi-g1 tables

liblouis/liblouis.h.in
The enum contains the official emph_ names.
The original constants (bold, italic, underline) are now #defines so
that code can test for their presence.
The comp_emph_1-3 #defines are based on the corresponding emph_
constants so that they can be independently removed or retained.
=> Define the emphclass bits in liblouis.h in a better way.

liblouis/compileTranslationTable.c, liblouis/liblouis.h.in
When cross-compiling 3.1.0 I get the following error:
```
-*- mode: compilation; default-directory: "~/src/liblouis-mingw/" -*-
Compilation started at Mon Mar  6 16:22:22
make LDFLAGS='-avoid-version -Xcompiler -static-libgcc'
Making all in gnulib
make[1]: Entering directory '/home/eglic/src/liblouis-mingw/gnulib'
make  all-recursive
make[2]: Entering directory '/home/eglic/src/liblouis-mingw/gnulib'
make[3]: Entering directory '/home/eglic/src/liblouis-mingw/gnulib'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/home/eglic/src/liblouis-mingw/gnulib'
make[2]: Leaving directory '/home/eglic/src/liblouis-mingw/gnulib'
make[1]: Leaving directory '/home/eglic/src/liblouis-mingw/gnulib'
Making all in liblouis
make[1]: Entering directory …
```
=> Add EXPORT_CALL to lou_getEmphClasses

tables/IPA.utb
uncomment some lines: some typos are from 'IPA extensions' unicode and not 'greek letters'.
=> 'Fix' IPA table

doc/liblouis.texi, liblouis/liblouis.h.in, tests/check_metadata.c, windows/include/liblouis.h
- removes all calls to the deprecated `lou_logPrint` function.
- marks `lou_logFile` and `lou_logEnd` as deprecated, because they only interact with `lou_logPrint`.
- Adds a short section to the docs explaining the api change. I have no idea if this reflects your intentions or the truth at all. There have been a lot of changes over the last years, which made understanding `git blame`s really hard.
Closes issue #233.
=> Documenting logging api deprecation, removing last internal usages

liblouis/compileTranslationTable.c
In lou_getEmphClasses, the destination pointer past to memcpy is a const char**, meaning that the strings are constant but the array itself isn't. However, memcpy takes a void* and MSVC doesn't seem to consider the multiple levels of pointers in this case.
To get around this, just explicitly cast to a void* when passing the destination to memcpy.
This warning is currently breaking building liblouis for NVDA, since we treat all level 1 warnings as errors.
=> Eliminate MSVC warning about different const qualifiers in compileTranslationTable.c

tables/en-ueb-chardefs.uti, tests/Makefile.am, tests/yaml/Makefile.am, tests/yaml/en-ueb-g2_backward.yaml, tests/yaml/en-ueb-g2_backward_no_dis.yaml
"?" was incorrectly being back-translated to "his". This occurred because the display opcode for "?" was after the punctuation opcode for "?".
Regression introduced in 5fff9d84 (#211).
Fixes #309.
=> en-ueb-g2.ctb: Fix back-translation of "?" to "this".

.gitignore, tests/Makefile.am, tests/compbrlAtCursor.c, tools/brl_checks.c, tools/brl_checks.h, tools/lou_checkyaml.c
Needs some more work, but I'm putting it up here to illustrate what I meant to do in #271.
=> Allow to test translations with cursorPos in brl_checks

configure.ac, python/setup.py.in
setup.py tries to import the louis module at build / install time.
However, this will fail if the package is being cross-built on
a host architecture other than the target architecture.
Instead, setup.py probably should be generated automatically by
autotools.
=> Python bindings: fix crossbuild.

tools/brl_checks.c
When built with --enable-ucs4, brl_checks.c was using the 16-bit
wide character functions instead of the 32-bit ones.
=> tools/brl_checks.c: use correct wide char type.

.travis/after_success/emscripten.sh, .travis/script/emscripten-build.sh, .travis/script/emscripten.sh
Disables the 2x 25MB builds with all table files embeded. They became virtually useless through changes in the upcoming liblouis-js version.
=> Disable tables embeded builds

.travis/after_success/emscripten.sh, .travis/before_install/emscripten.sh
- Previous merged PR had 2 serious quality issues and should not have made it into the repo. I am sorry.
- Also pins the version of liblouis-js to a specific commit instead of master. Avoids issues we previously had with both repos being out of sync.
=> Hot Fix + Pin liblouis-js version

liblouis/lou_backTranslateString.c, tests/yaml/en-ueb-g1_backward.yaml, tests/yaml/en-ueb-g2_backward.yaml
Back-translations were not detecting word contractions when followed by punctuation. Forward translations were already producing the expected result.
This commit adds a check for `CTC_Punctuation` together with `CTC_Space` when detecting contractions in `lou_backTranslateString.c`. Similar checks were already being done in other places such as in: [master/liblouis/lou_translateString.c#L2225](https://github.com/liblouis/liblouis/blob/master/liblouis/lou_translateString.c#L2225) (for forward translations).
Example: When using "en-ueb-g2.ctb", "12-2" would back-translate to "b," instead of "but,".
The issue is particularly important for the usage of other conjunctions such as "although".
Tests which verify the back-translation behavior with and without contractions are also included.
=> Fix back-translation for contractions followed by punctuation

liblouis/compileTranslationTable.c, tests/yaml/en-ueb-g2_backward.yaml
For example, the dot pattern for "thing" (⠹⠬) was previously being back-translated as "thising".
This occurred because certain uplow opcodes included cells such as ⠬ in a multi-cell pattern and the table compiler was setting a space attribute for any cells in a multi-cell uplow opcode. I don't know why (and the code pre-dates version control), but I can't think of a good reason and removing this doesn't break any tests.
=> UEB grade 2: Fix back-translation of whole word contractions followed by other contractions.

liblouis/lou_backTranslateString.c, tests/yaml/en-ueb-g2_backward.yaml
When checking for the end of a word, exclude begword and midword rules from rules which are immediately treated as meaning this is not the end of a word, as we don't know whether they apply yet. Subsequent input will allow us to determine whether the word continues.
Fixes #360.
=> UEB g2: Fix back-translation for contractions followed by punctuation.

.gitignore, configure.ac, windows/Makefile.am, windows/utils/Makefile.am
This is required to build with MSVC but was missing from `make dist`.
=> Add the windows/utils directory to the tarball

tables/es-chardefs.cti
Still waiting for feedback on this change from reporter.
Also queried the reporter if there is an official standard publicly available. At least this change is correct according to [Wikipedia], but their sources seem a bit lacklustre.
[Wikipedia]: https://en.wikipedia.org/wiki/Spanish_Braille
=> "¡..!" should be translated as "235 ... 235".

tables/hu-hu-g1.ctb, tables/hu-hu-g2.ctb, tables/hu-hu-g2_exceptions.cti
Since jul of 2017, some dot combinations changed in hungarian grade1 and grade2 standard. This fix adapt these changes.
Before the 3.3 release publication please merge this change into Liblouis repository master branch.
=> Hungarian grade tables: adapt new 2017 grade standard changes

windows/Makefile.nmake
Broken by 0350ec0005cb51d06383198739ece70c9c2f8e7c and c9e7460757fc6b388a1eb8baf357fbe085e82a11.
=> Fix NMakefile for findTable rename and wrappers removal

tables/mn-MN.utb, tests/yaml/mn-MN_harness.yaml
The Mongolian standard capp letter sign was changed to dot 6 following the changes of ueb English. Therefore, I have changed the former cap letter sign which was dots 45, I changed it to dot 6 as same as English UEB braille.
=> Cap sign change

tables/zh-tw.ctb
Summary of changes:
1. Add \x2060. This looks like one space character.
2. Add missing subscript translations (\x2095 to \x209C).
3. Add \xF0B7. It is privately used for list item sign somewhere (such as
&nbsp;&nbsp;&nbsp;Microsoft Word).
4. Add -46 into \x2488-\x249B to indicate a full stop.
5. Assign the same dot pattern as "st" to both \xFB05 and \xFB06. Also add
&nbsp;&nbsp;&nbsp;\x017F as 234 (lowercase s).
6. Fix some Chinese words and Nemeth symbols brailled incorrectly.
Reviewed by:
&nbsp;&nbsp;&nbsp;&nbsp;Coscell Kao &lt;coscell@gmail.com&gt;
&nbsp;&nbsp;&nbsp;&nbsp;嘯傲俠羽 &lt;crazy@mail.batol.net&gt;
=> Update zh-tw.ctb to version 2017-11

tests/yaml/issue-400.yaml, tests/yaml/issue-401.yaml
This simplifies the strings and cases being tested, and adds a few new testcases for #400, to test cancellation of capitals as well as numbers.
=> Updated tests for #400 and #401

tables/UEBC-g2.ctb, tables/en-GB-g2.ctb, tables/en-gb-g1.utb, tables/ukchardefs.cti
This is an attempt to salvage the updates from #29. I ported the tables to the new syntax used since version 3.0 of liblouis.
The test still fail because `ukchardefs.cti` now defines `punctuation ( 2356` as opposed to `punctuation ( 12356` as it was previously. That is not  a problem in itself. The problem is that `UEBC-g2.ctb` still uses the dot pattern `12356` in several places:
```
tables/UEBC-g2.ctb:289: error: Dot pattern \12356/ is not defined.
tables/UEBC-g2.ctb:430: error: Dot pattern \12356/ is not defined.
tables/UEBC-g2.ctb:490: error: Dot pattern \12356/ is not defined.
tables/UEBC-g2.ctb:491: error: Dot pattern \12356/ is not defined.
tables/UEBC-g2.ctb:492: error: Dot pattern \12356/ is not defined.
tables/UEBC-g2.ctb:493: error: Dot pattern \12356/ is not defined. …
```
=> Updates to SEB British Braille Table

doc/liblouis.texi
This is basically just taken from Mikes email and wrapped in some texinfo markup.
What needs to be done is to also the other opcodes that are refered to like all the sequence opcodes.
Fixes #188
=> Add preliminary documentation for the match opcode

NEWS, configure.ac, doc/liblouis.texi, tests/Makefile.am, tests/yaml/Makefile.am, tests/yaml/broken_equals_operand.yaml
- Fixed the documentation accordingly and 
- added Bues test case
=> No longer mark = as deprecated

liblouis/compileTranslationTable.c, liblouis/lou_translateString.c, liblouis/maketable.c, liblouis/pattern.c, liblouis/utils.c, tools/lou_checkyaml.c, tools/lou_tableinfo.c
-Wunused-parameter
-Wunused-but-set-variable
-Wunused-function
-Wunused-result
-Wunused-variable
-Wold-style-declaration
-Wmissing-braces
-Wswitch
This is related to #322 but doesn't actually fix any warnings that are
mentioned in there. It does however fix some warnings that are listed
in
https://www.freelists.org/post/liblouis-liblouisxml/liblouis-340-has-been-released,1
=> Fix warnings such as -Wunused-parameter, etc

liblouis/lou_translateString.c
This code removes the dead code to handle `compbrl` from the `for_updatePositions` function as it is now handled 
- The first commit simply removes that code
- Some parameters that were used by the removed code are no longer needed. Hence the second commit removes the unused parameters in all involved functions
- The third commit removes a test that is now always true since the same condition is tested further up in the while loop
This PR fixes #502
=> Remove compbrl handling from for_updatePositions

tables/en-us-brf.dis, tables/text_nabcc.dis
This touches the issue described in #503, although apparently there's very little to no data available about mappings between dots and chars used internally in various braille notetakers. In particular, there's very little information on mappings of dot combinations with dots 7 and/or 8. Furthermore, it seems that these mappings might be vendor- or locale-dependent. If that's the case, I guess we can consider #503 as fixed, or just lacking further information.
=> Display table fixes

tables/fr-bfu-g2.ctb, tests/braille-specs/fr-bfu-g2.yaml
This PR fixes some backtranslation errors about 'a', 'e' and 'y' isolated in french grade 2 table.
Before: "⠁ ⠑ ⠽" -> "A E Y" instead of "a e y". It was necessary to escape them with letsign ("⠰⠁ ⠰⠑ ⠰⠽").
It also adds some yaml tests for that.
=> fr-bfu-g2.ctb: backtranslation fixes about 'a', 'e' and 'y'

liblouis/compileTranslationTable.c
_lou_resolveTable() should clean up the list of resolved tables returned from the default resolver, since a copy is returned to caller.
=> Fix leaks when using default table resolver

tools/brl_checks.c, tools/brl_checks.h, tools/lou_checkyaml.c
If not try a few more times with a larger output buffer
Fixes #495
AFAICT this implements what is asked for in the issue. However due to this change the test suite no longer passes. Is this a problem in this patch or in the test suite?
=> Ensure that inputLength equals actualLength

tools/Makefile.am
This fixes build against automake 1.16.
=> Enable automake to generate dependencies for libbrlcheck.la

NEWS, tools/lou_allround.c
Solves #642 
Also, now the flags are refered to by name instead of absolute values.
Other things we could do in this PR:
- Remove the last traces of pass1Only in liblouis.h and lou_translatestring.c.
- Add the most commonly used modes as command line parameters to the other tools, e.g. -p or --partialTrans.
=> Tidy up mode flags in lou_allround.c

liblouis/metadata.c
When UNICODE is defined as preprocessor macro, Liblouis refuses to build as part of NVDA because WIN32_FIND_DATA translates to WIN32_FIND_DATAW. This pr explicitly uses the WIN32_FIND_DATAA type.
Having said that, I'm not sure whether liblouis should keep on using the ANSI version of FindFirstFile. But, it looks like Liblouis' API is quite char (not w_char_t) oriented.
=> Fix build error when UNICODE is defined

doc/liblouis.texi, liblouis/liblouis.h.in, python/louis/__init__.py.in
Fixes #187 
Fixes #55
Related to https://github.com/nvaccess/nvda/issues/6695
The Python bindings do not yet support wide characters. This pr fixes this, while also removing the exception raising in case python and liblouis char sizes differ.
Implementation strategy based on ideas proposed by @jcsteh in https://github.com/nvaccess/nvda/issues/6695#issuecomment-320538695
1. The Python bindings need to know the number of bits used for widechar (16 or 32) by the compiled liblouis. This is accomplished by once calling lou_charSize when initializing the module, saving the value to wideCharBytes
2. Use utf_32_le for 32 bit widechars, and utf_16_le for 16 bit widechars.
3. Tell ctypes to use c_char_p instead of c_wchar_p so that we get raw bytes. use POINTER(c_char) instead of c_char_p. c_char_p …
=> Patch Python bindings to support both 16 and 32 bit widechars, add more functions from the liblouis api

NEWS, tables/nl-BE-g0.utb, tables/nl-NL-g0.utb, tables/nl-chardefs.uti, tables/nl-g0.uti, tables/nl.tbl, tables/nl_BE.tbl, tests/braille-specs/nl-NL-g0_harness.yaml, tests/braille-specs/nl-g0_harness.yaml
This updates the Dutch tables to the [braille standard 2017](http://braille-autoriteit.org/algemeen-gebruik/versie-2017-van-zespunts-standaard).
There is still much more work to do beyond updating the braille standard:
* Finally make emphasis work analogous to capitalization, i.e. an `emphmodechars` opcode.
* Include all examples from the braille standard as tests, ordered by section.
* Remove tests/tweaks implemented by non-Braille Autoriteit agencies to get a purer table.
- Improve backtranslation.
I don't address these points in this PR. However, I do want to find a better way to handle the various types of single quotes in `capsmodechars`.
=> Update the Dutch tables to the braille standard 2017.1

tables/Pl-Pl-g1.utb, tests/Makefile.am, tests/braille-specs/Makefile.am, tests/braille-specs/Pl-Pl-g1_backward.yaml
This simply moves all Polish diacritics to the beginning of the table, because otherwise when back-translating they are treated as a different symbols.
=> Improve Polish Grade 1 table, to make back-translations of diacritics working

NEWS, liblouis/internal.h, liblouis/liblouis.h.in, liblouis/lou_backTranslateString.c, liblouis/lou_translateString.c, liblouis/utils.c
and use that to check mode input. This is turn is then used to reject any deprecated modes such as pass1Only
This is IMHO a cleaner implementation of #645. It also removes the pass1Only flag.
The layout of the code is a bit odd. We have an array (`validTranslationModes[]` in `utils.c`) that contains all the valid modes. Naturally this is very tightly coupled to the enum type declaration in `liblouis.h.in`. Maybe these two declarions should be closer together.
Also since this is really an internal helper function it should maybe not be in `internal.h` which is despite its name semi-public
Also the other functions in `utils.c` also seem to be publicly exported functions, whereas `isValidMode` is strictly internal. Should it go into another utils file?
=> Implement a isValidMode function

tools/brl_checks.c, tools/lou_checkyaml.c
With the possibility to define one test for multiple tables in
checkyaml it is not always clear in which table a problem occurred.
This patch should help to locate the table that is the culprit for a
failed test.
=> If test fails also print the associated table name

python/louis/__init__.py.in
#633 introduced support for registering log callbacks in the python bindings, however, this bugged in two ways:
1. Both the ctypes function type and the registerLogCallback argument were named logcallback. The functype is now LogCallback and the function argument is logCallback
2. Even though this was advertised in the doc string, registerLogCallback didn't allow providing None to revert to the default callback. This was because ctypes used argument type checking. Type checking is now done using an isinstance check in the registerLogCallback wrapper function.
=> Python: Fix None callback registration

liblouis/lou_backTranslateString.c, liblouis/lou_translateString.c
This is a quick fix for the memory issues that occur when using GCC 9 (also see #686). I didn't analyze the code in detail yet and therefore only patched the parts that led to segmentation faults in the test suite. Maybe some more changes have to be applied.
=> Fixed memory leaks created by block scope compound literals

tests/yaml/broken_equals_operand.yaml
How does this currently work in forward trans with chars that take up two or more Braille cells? The function getdotsforchar() only returns one widechar and seems to assume that there is a single cell representation for each char, which is false for most or all literary tables.
=> Make equals operand work with back-translation

tables/en-us-g2.ctb, tests/braille-specs/en-us-g2-dictionary_harness.yaml
This changes the dot pattern for the "er" of "anterior" from 23456 to 12456.
=> Corrects dot pattern for anterior.

NEWS, tables/no-no-chardefs6.uti, tables/no-no-g0.utb, tables/no-no-g1.ctb, tables/no-no-g3.ctb, tables/no-no-latinLetterDef6Dots_diacritics.uti, tests/Makefile.am, tests/braille-specs/Makefile.am, tests/braille-specs/no_backward.yaml, tests/braille-specs/no_harness.yaml
The purpose of this update is mainly to fix some problems caused by an update
in April 2015, that led to misbehavior when used with devices that don't
understand unicode bbraille. Some characters are moved to get higher
priority to output from liblouis.
In addition, I've added/fixed braille representation for some capital
accented letters that previously was wrong. These chars are added to the test file
no_harness.yaml as well.
Still there are one issue that I hope someone else can look into: the
begcomp/endcomp construct. I've added a test case, with status xfail, in the
file no_backward.yaml, to demonstrate the problem. The problem is not
introduced with this update.
=> Update the Norwegian tables

python/louis/__init__.py.in
Fixes #698
! Not finished/optimized for Python 2.
=> Python binding: allows translate if tables are located in path with non-ASCII characters

NEWS, python/louis/__init__.py.in
Reverts liblouis/liblouis#699
Based on the discussion in #699 I'm reverting this
=> Revert "Python binding: allows translate if tables are located in path with non-ASCII characters"

tables/en-ueb-g2.ctb, tests/braille-specs/en-ueb-g2_backward.yaml
Resolution for issue #562 (where 'qk' was back-translating as "quick's").  
It appears that when someone added an annotation to UEB Rule 10.9.3, that annotation was inadvertently inserted into the middle of the relevant rule rather than at the end.
=> Fix UEB contracted back-translation of 'qk' and add YAML verification test

tables/en-ueb-g2.ctb, tests/braille-specs/en-ueb-g2_backward.yaml
Partial resolution to issue #572 regarding the UEB issues only.
Fixed "⠋⠌" erroneously back-translating as "first's" rather than "first". When the table was edited ao annotate this as flowing from UEB Rule 10.9.3, the rule was inadvertently inserted into the midst of the rule breaking it.
Fixed "⠭⠄⠎" erroneously back-translating as "x's" rather than "it's".  The dot pattern for "x" was misspecified in the table as 1-3-4-5 (N) rather than 1-3-4-6 (X).
Adds YAML tests for verification.
The UK English grade 2 "double L" issue also raised in #572 is not addressed by this pull request.
=> Fix UEB contracted back-translation of "first" and "it's"

tables/en-GB-g2.ctb, tests/braille-specs/en-GB-g2_backward.yaml
Resolution to remaining problems reported at issue #572 relating to the UK grade 2 table.
Resolves numerous problems surrounding the (ll)=(little) and (bel)=(below) contractions.
On back-translation, the letters "ll" were being back-translated as 'little' regardless of where they appeared in the word (resulting in e.g. ball => balittle).  
On back-translation, "(be)little" was erroneously back-translated as "belowittle".
On back-translation, "(be)(ll)d" was erroneously back-translated as "belowld".
On forward-translation, "belittle" was being abbreviated to "(be)ll" creating ambiguity between belittle and bell.
This patch corrects the above issues and adds YAML verification tests based on examples in UKAAF standards.
=> UK English Braille Grade 2 - Correct erroneous back-translation of 'll'

README
I am not familiar with these Linux's procedures. `./configure` do nothing so I tried this `./autogen.sh`.
=> Documentation / README: './autogen.sh' missing in the installation steps

configure.ac
because this resulted in a runtime dependency on libyaml in liblouis.dylib if libyaml is installed on the compiler machine.
Note that ideally liblouis.dylib should never depend on libyaml, only lou_checkyaml should.
A better solution might be to use the `action-if-found` argument:
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Libraries.html#Libraries
=> Don't add -lyaml to LIBS if --with-yaml=no is specified

tables/Makefile.am, tables/hu-hu-comp8.ctb, tables/hu-hu-g1.ctb, tables/hu-hu-g1_braille_input.cti, tables/hu-hu-g2.ctb
Hy Chris,
I doed first release with hungarian grade1 Braille input related.
If this is possible, please merge this pull request with the Liblouis master branch before Liblouis 3.10.0 release coming out.
I doed few small modifications with hu-hu-comp8.ctb, hu-hu-g1.ctb, hu-hu-g1.ctb, hu-hu-g2.ctb tables related. I merge these changes with one commit.
Attila
=> Add Hungarian grade1 Braille input related rules, and some modifications to the Hungarian table files

tables/nl-g0.uti, tests/braille-specs/nl-g0_harness.yaml
For example, when "2DE" happens inside a phrase in all-caps, it appears as the number "245".
@dkager Can you confirm that the new test is correct?
=> Issue in Dutch with numbers inside all-caps phrases

.travis.yml, .travis/before_install/mingw.sh, liblouis/compileTranslationTable.c, liblouis/internal.h, liblouis/lou_backTranslateString.c, liblouis/lou_translateString.c, liblouis/utils.c, tools/brl_checks.h, tools/lou_allround.c, tools/lou_checkhyphens.c, tools/lou_checktable.c, tools/lou_checkyaml.c, tools/lou_debug.c, tools/lou_tableinfo.c, tools/lou_trace.c, tools/lou_translate.c
Unfortunately not every version of `clang-format` produces the same output given the same config file. For that reason when upgrading `clang-format` we also have to re-format the source. Luckily the changes are pretty small.
Since I upgraded my machine I no longer have clang-format5 which we are currently using on travis. 
This PR upgrades the Travis build environment to Xenial which has Clang7. I locally have Clang8 and re-formated the source with that. They seem to produce identical output.
=> Upgrade clang-format

liblouis/compileTranslationTable.c, liblouis/internal.h
It was only used in liblouisutdml and since the internal API is no longer exported it makes no sense to have this call in the API.
=> Remove the _lou_getLastTableList function

tables/fr-bfu-comp68.cti
Fix a small typo in the character description for U-0305 (math complex conjugate)
Was "congugué de", should read "conjugué de".
=> tables/fr-bfu-comp68.cti: Fix small typo

tables/de-de-comp8.ctb
RIGHT SINGLE QUOTATION MARK comes up regularily when browsing the web with
NVDA.
=> tables/de-de-comp8.ctb: add a mapping for 0x2019

NEWS, tables/es-g2.ctb
To do (user suggestions): 
Add dot 5 when alphabet letters are presented by themselves, except q and w
In case of q and w,  add dots 5 and 6 by themselves to avoid confusion with accented variants/derivatives of these words.
Fixes are detailed in commits, however including them here for completeness:
Added new remarks (as comments) regarding use of pronouns with sources.
corrected contraction and derivatives: único. It was previously dots 23456-13 and should have ben 23456-14
word: ese also corrected
added: numerosas, cuya
Skipped: Sólo. Its accentuation has been discouraged at least since 1959, see RAE rules.
corrected: aquéllos, aquéllas an other commonly missaccented demonstrative pronouns conforming to the latest RAE rules. 
Removed: contraction 5-1356, esté, it served no purpose at …
=> Spanish grade 2 fixes and updates

NEWS, tables/wordcx.dis
It's a display table that matches chars used by Word CX to display
braille patterns on screen. I know for sure that Word CX is used in
Norway and Sweden, and maybe also in other countries. I'm quite sure
that the char mapping is the same in the two countries, and because of
that, I named the table wordcx.dis, not no-no-wordcx.dis.
=> Add a display table to match Word CX

NEWS, liblouis/compileTranslationTable.c, liblouis/internal.h, tools/lou_debug.c
It is still possible to use a translation table as a display table, and the API is not changed yet.
The next steps are
- to add a separate argument for the display table to the API
- to add new options for the display table to the tools
- to use the new API to implement `display: ...` in the "lou_checkyaml" tool
- to add deprecation warnings when a display table contains rules other than `display`
- to make it possible to specify a display table that is not really a table but implemented in C (notably for Unicode braille, and possibly the dotsIO mode can be replaced with a special display table)
- to add more options for controlling the displaying, like e.g. ignoring virtual dots (see https://github.com/liblouis/liblouis/issues/750)
=> Internally separate display from translation

tools/brl_checks.c, tools/lou_checkyaml.c
- Report expected failures
- Print the table under test also in hyphenation mode
- Print the table under test also for expected failures
- Make a test fail if it resulted in a expected pass for one of the tables under test
- Count every test once for every table under test in the total number of tests
=> Some improvements to lou_checkyaml test reporting

AUTHORS, NEWS, tables/nl-chardefs.uti, tests/braille-specs/nl-g0_harness.yaml
The bullet and dot operators in the Dutch chardefs must be converted to (236).
=> tables/nl-chardefs.uti: Bullet and dot operators fix

python/louis/__init__.py.in
1. FIxed a typo: createEncodedByeString > createEncodedByteString. This typo was probably introduced due to a bad search/replace.
2. On Python 3, an UnicodeEncodeError was raised when trying to translate utf-16 surrogate characters. NVDA suffers from this issue in command consoles, where surrogate characters seem to be allowed. Using the surrogatepass error handler ensures that behavior is similar to the behavior on Python 2.
=> Python wrapper: createEncodedByeString > createEncodedByteString and allow surrogates on Python 3

tables/de-g0.utb, tables/de-g2.ctb
Changed "translation" to "direction".
=> Marked Current German g0 and g2 table correctly as forward only tables.

configure.ac
It is not actually used, and even if it was, PKG_CHECK_MODULES already does
the detection, and with support for cross-compilation, so we should not try
to detect pkg-config by hand, it only reduces support.
=> Remove explicit detection of pkg-config

liblouis/compileTranslationTable.c
Warning: I'm not totally confident for this patch, (I'm a beginner in C), so please review it carefully. :)
Fixes #854 
* With current releases: see #854
* With this patch: see below
```
$ echo "test"|valgrind --track-origins=yes --leak-check=full --show-leak-kinds=all -v ~/app/liblouis_test/bin/lou_translate en-ueb-g1.ctb,foobar.ctb
==112557== Memcheck, a memory error detector
==112557== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==112557== Using Valgrind-3.14.0-3a3000290b-20181009X and LibVEX; rerun with -h for copyright info
==112557== Command: /home/andreabush/app/liblouis_test/bin/lou_translate en-ueb-g1.ctb,foobar.ctb
==112557== 
--112557-- Valgrind options:
--112557--    --track-origins=yes
--112557--    --leak-check=full
--112557--    --show-leak-kinds=all …
```
=> Avoid a memory leak when several tables are specified with some of them that can't be resolved

liblouis/compileTranslationTable.c, liblouis/internal.h, liblouis/liblouis.h.in, liblouis/lou_backTranslateString.c, liblouis/lou_translateString.c, liblouis/maketable.c, tests/braille-specs/da-dk-g18.yaml, tests/braille-specs/fr-bfu-comp6.yaml, tests/braille-specs/fr-bfu-g2.yaml, tests/braille-specs/no_harness.yaml, tests/braille-specs/zh-tw.yaml, tests/charToFallbackDots.c, tests/getTable.c, tests/yaml/Makefile.am, tests/yaml/multipass-vs-match.yaml, tests/yaml/multipass-vs-match_common.uti, tools/brl_checks.c, tools/brl_checks.h, tools/lou_allround.c, tools/lou_checkyaml.c, tools/lou_debug.c, tools/lou_maketable.d/utils.py, tools/lou_trace.c
This is the next step after #789.
There are two phases to a braille conversion:
1. **translation**: liblouis uses the rules in the translation table to convert characters to dots
2. **display**: display the dots as characters. Usually liblouis uses the characters defined in `display` rules (in display tables) but as a fallback it uses mappings defined in the translation table, e.g. `letter` rules
This PR aims to separate these two concepts at least internally
=> Further separate display from translation

tools/lou_translate.c
`lou_translate` has had an undocumented feature to directly specify a file to translate instead of piping it in via `stdin`. This code crashes if a non-existing file is passed in (see #849).
This PR takes a different approach at preventing this crash than the previous PR (#850).
In the spirit of _less is more_, instead of making the code more tamper-proof and documenting it, we simply remove this feature.
The behaviour can easily be had by using `lou_translate foo.tbl < bar.txt`
Fixes #849
Supercedes #850
=> Remove the second, undocumented argument to lou_translate

NEWS, tables/Makefile.am, tables/nl-comp8.utb, tests/Makefile.am, tests/braille-specs/Makefile.am, tests/braille-specs/nl-comp8_harness.yaml
This adds a table for the 8 dot Dutch Computer Braille standard, which is currently in draft.
Closes #870
=> Dutch 8 dot braille table draft

doc/liblouis.texi, liblouis/compileTranslationTable.c, liblouis/lou_translateString.c, tests/yaml/multipass-forward.yaml
Fixes https://github.com/liblouis/liblouis/issues/558 for forward translation.
This is the part of https://github.com/liblouis/liblouis/pull/860 that deals with forward translation only, and without the function renaming.
=> Fix endless loop

tables/Pl-Pl-g1.utb, tables/pl-pl-comp8.ctb, tests/braille-specs/Pl-Pl-g1_harness.yaml, tests/braille-specs/pl-pl-comp8_harness.yaml
This PR implements the following:
- Closes #804
- Removes some unneeded mitnum symbols from the Polish Grade 1.
- Fixes some symbols which weren't defined according to the specification.
- Makes it possible to type dot from a braille keyboard.
- Adds Greek letters  and some commonly used math operators to both Grade 1 and computer braille table,
I've added tests for the first wave of changes - creating them for simple characters such as Greek letters makes no sense in my opinion.
=> Additional fixes to Polish grade 1

liblouis/internal.h
rules use 64bit fields, so we need to align them on 64bit on architectures
which require it (e.g. sparc64), and that will also make other architectures
slightly faster.
Fixes #890
=> Align translation rules on 64bit

liblouis/compileTranslationTable.c
When doing some packaging for RHEL 8, I came across these issues as reported by Coverity. I have not done much testing other than running the test suite, and I do not know liblouis well, so a careful look over the changes is probably in order. Thanks!
=> A couple of small Coverity fixes

liblouis/lou_backTranslateString.c, tests/yaml/multipass-backward.yaml
This is the part of https://github.com/liblouis/liblouis/pull/860 that was not included yet and is OK to include.
=> Fix endless loop in makeCorrections and translatePass (backTranslateString.c)

.github/FUNDING.yml
I've added Liblouis to IssueHunt: https://issuehunt.io/r/liblouis/liblouis. This enables us or anyone else to put bounties on specific issues. I haven't installed the IssueHunt app on the repo yet. This is needed in order to enjoy all of the features such as bounty requests, bot commenting, automatic PR submission and automatic rewarding, but I'll wait a bit with that.
If we add this YAML file it should create a sponsor button. Later we can add more stuff to it, e.g. I'm planning to sign up with GitHub Sponsors.
=> Enable sponsor button

NEWS, python/louis/__init__.py.in
This PR fixes #895: rather than sys.getfilesystemencoding(), we use locale.getpreferredencoding as advertised by @lukaszgo1.
Also, fixes another bug, thanks to @leonardder: `getTypeformForEmphClass` was passed a decoded string on Python 3 instead of an encoded one.
=> Python bindings: always use mbcs on windows to encode file path, `getTypeformForEmphClass` fix and clean up

NEWS, doc/liblouis.texi, liblouis/compileTranslationTable.c, liblouis/internal.h, liblouis/lou_translateString.c, tests/yaml/repword.yaml
With this opcode you can indicate that a part of a word between a start and end mark is repeated. With the existing repword opcode you could only repeat a whole word.
This fixes issue https://github.com/liblouis/liblouis/issues/787
Also fixed some small issue with the existing repword opcode.
=> Add new opcode rependword

doc/liblouis.texi
- I've removed all mentionings of "context" because I don't think it was a useful concept to explain emphasis indication, and moreover it was not clear what it meant. Now I speak of "scope" instead.
- I've changed the section about fallback behavior a bit because it was too simplistic and not accurate.
- I've removed the "Symbol" section because it made no sense to me and I have no idea where you got that from. If you remember what this was about we can add a section again.
Next (when this is merged) I will update the documentation for https://github.com/liblouis/liblouis/pull/897 and https://github.com/liblouis/liblouis/pull/894.
=> Rework documentation of emphasis opcodes

tables/zh-tw.ctb, tests/braille-specs/zh-tw.yaml
It is a minor update of this table. Except the issue of adding emoticons, other rules are stable in principle. That is, if no change is made, zh-tw.ctb update may be absent from some future releases of liblouis.
Summary of changes:
* Add some more Chinese translation exception rules.
* Update copyright declarations.
Reviewers:
* Coscell Kao &lt;coscell@gmail.com&gt;
* Victor Cai &lt;surfer0627@gmail.com&gt;
=> Update zh-tw.ctb version to 2020-02

liblouis/compileTranslationTable.c, liblouis/internal.h
and at the same time decrease `LETSIGNSIZE` for `noletsignbefore` and
`noletsignafter` (by introducing two more constants `LETSIGNBEFORESIZE`
and `LETSIGNAFTERSIZE`.
This will allow for 256 letsign characters while keeping the size of
the table the same because we decrease the size of the `noLetsignBefore`
and `noLetsignAfter` array.
This fixes #529 in a simplistic but good enough way and helps with #921.
=> Increase LETSIGNSIZE to 256

tables/no-no-8dot-fallback-6dot-g0.utb, tables/no-no-8dot.utb, tables/no-no-g0.utb, tables/no-no-g1.ctb, tables/no-no-g2.ctb, tables/no-no-g3.ctb, tables/no.tbl
Input of Norwegian tables is expected to be normalized to NFC (fully composed).
Fixes https://github.com/liblouis/liblouis/issues/923
=> Add "unicode-form" metadata field to Norwegian tables

python/louis/__init__.py.in
Fixes #895 
Closes #877
This pr addresses the following:
* It removes Python 2 support, as Python 2 is no longer maintained by Python. This way, we no longer have to bother about maintaining compatibility
* Rather than sys.getfilesystemencoding(), we use locale.getpreferredencoding as advertised by @lukaszgo1. I think this more closely resembles what liblouis expects from us.
* It adds type annotations to the several functions
* It fixes two issues in the wrapper:
+ getTypeformForEmphClass was passed a decoded string on Python 3 instead of an encoded one
+ The same applies to compileString. We encoded the input string, but never used that encoded one when passing it to liblouis
I'm opening this as draft, as it requires some testing, but I intend it to be finished before 3.13.
cc …
=> Drop Python 2 support

doc/liblouis.texi, tests/yaml/capitalization.yaml
Part of https://github.com/liblouis/liblouis/pull/928 that was not merged yet. There was a discussion going on about how to best do it. We want it to kind of stand on its own but at the same time don't create too much duplication with the "emph" opcodes (see https://github.com/liblouis/liblouis/pull/928#issuecomment-616656702).
=> Fix documentation of "caps" opcodes

NEWS, extra/generate-display-names/display-names, tables/Makefile.am, tables/bel-comp.utb, tables/bel.utb, tables/ru.ctb, tests/Makefile.am, tests/braille-specs/Makefile.am, tests/braille-specs/bel.yaml
Hello!
These are two Belorussian braille tables - for literary and computer braille. They/re based on the Russian braille code.
I'll add the NEWS-file with https://github.com/pull/1041 later, this can be merged without news.
Andrey
=> Adding new Belorussian braille tables

NEWS, tables/ur-pk-g1.utb, tables/ur-pk-g2.ctb, tests/braille-specs/ur-pk-g2.yaml
@egli @bertfrees 
I realise this might be too short notice for release on March 8th release but some important updates to Urdu tables and tests following further input from Urdu Braille proof reader in Pakistan:
- Dot 4 not dot 1 used for SUPERSCRIPT ALEF (\x0670).
- Revised definition for ARABIC LIGATURE ALLAH ISOLATED FORM (\xFDF2).
- Contraction dots 135 no longer used for ٹھ. Use uncontracted 246-236 instead. 135 and 5-135 still used as word signs.
- Contraction 35 used for ان and اِن whether as a whole word or within a word
- Contraction 36 used for بے not for بی at the beginning of words.
- Contraction 136 used for اَور and اور
- Dots 3-3 used for repeated words (not 6-6 as previously)
=> Improvements to Urdu tables and added tests.

liblouis/lou_translateString.c, tools/lou_trace.c
- some rules were printed even though they were not applied
- use %xxx syntax to render single custom attribute in multipass expression
- support multipass rules with reference to swap rule
- fix rendering of multipass rules with attributes
=> Various fixes to lou_trace

NEWS, tables/en-us-comp6.ctb, tests/braille-specs/en-us-comp6.yaml
Hello again,
We've got a report that apostrophes are not translated correctly. As I saw the table contains just one type of apostrophe, but the client wanted to use "right single quotation mark" and "acute accent" for the same purpose.
I've added two more definitions for those.
=> Apostrophe update in En-US computer braille

windows/Makefile.nmake
I fixed the nmake build by changing cl into clang-cl. In other words, it's now using clang as we do in NVDA. Newer versions of visual studio 2019 add LLVM to the path of the tools command prompt, so the procedure for building liblouis with nmake now works again.
=> Fix nmake build

NEWS, tables/ru-litbrl-detailed.utb, tables/ru-litbrl.ctb, tests/braille-specs/ru.yaml
I'm trying to add support of back translation for the Russian literary braille code. It's quite difficult because it's necessary to translate of letters of different alphabets.
Everything seems to be OK, excepted translation of decimals. I don't know why, but 'midnum' opcode doesn't work as expected when back translating. lou_trace shows that this opcode works, but after the decimal comma we have a letter instead of a digit. While I haven't figured out how to fix it.
The tests for back translation are also provided. Now one is failure, with decimals.
=> Ru-litbrl.ctb: supporting back translation

liblouis/compileTranslationTable.c, liblouis/lou_translateString.c, tables/afr-za-g2.ctb, tables/en-ueb-chardefs.uti, tables/ms-my-g2.ctb, tables/spaces.uti, tests/braille-specs/spaces.yaml
I start with some code cleanup and refactoring, and then I move on to making the compilation functions more strict by not ignoring compilation errors and aborting immediately when the first error is found. The error reporting has also been improved a bit. Thanks to these changes I was able to find a bug in the code and two errors in the tables. I fixed the bug and the two rules are commented out for now. I think I managed to fix them (locally) but would like the table authors to confirm this, and also add tests for these rules.
=> Refactoring of compileTranslationTable.c

liblouis/compileTranslationTable.c, tests/yaml/issue-332.yaml
See https://www.freelists.org/post/liblouis-liblouisxml/SV-Translate-Combined-Cap-Letters,2
An always rule starting with an undefined character would not work when that character was given an attribute (with the "attribute" opcode).
Related to commit bdaeb4c.
=> Fix bug discovered by Dang Hoai Phúc

NEWS, tables/Pl-Pl-g1.utb, tables/pl.tbl, tests/braille-specs/litdigits6Dots_backward.yaml, tests/braille-specs/pl-g1.yaml
This pull request:
- Uses correct representation of indexes for squared, cubed etc.
- Used correct representation for fractions (I haven't added any new to the table just made sure that one present are shown according to the specification)
- Changes symbol used for underscore from dots 46 to 6 (the former has been too similar to capital letter sign confusing users)
While at i I've also updated metadata of the table. The change from "grade 1" to "literary" is necessary since in Poland Grade 1 means the first level of contractions and the current table does not implement any contractions. Also "grade 1" in itself means nothing since there are two standards of contractions in Poland so with the former description it was not clear which one this table implements.
=> Small fixes to Polish G1

tests/braille-specs/no_harness.yaml
See: nlbdev/pipeline#214
Currently capitalized words are prefixed with "⠠⠠" (6-6). When there are multiple capitalized words after each other, then the first word should be prefixed with "⠠⠠⠠" (6-6-6) and the last word should be suffixed with "⠠" (6).
(PR only contains updated tests. Needs implementation.)
=> Norwegian: fix tests for handling of punctuation when there's two or more capital words

tests/Makefile.am, tests/yaml/Makefile.am, tests/yaml/issue-963.yaml
dot 7 capitalization indicator remains active when it shouldn't
See https://github.com/liblouis/liblouis/issues/963
=> Add test for issue #963

.github/workflows/macro.yml, configure.ac, liblouis/compileTranslationTable.c, liblouis/internal.h, tests/Makefile.am, tests/yaml/Makefile.am, tests/yaml/macro.utb, tests/yaml/macro.yaml
The syntax is explained in [the test](https://github.com/liblouis/liblouis/blob/55b29f2458ff19a6f607497eea1c330616e7b4df/tests/yaml/macro.utb). It's a very minimalist mechanism to perform string substitutions, with positional arguments. It's similar to e.g. [user-defined functions in Make](https://www.gnu.org/software/make/manual/html_node/Call-Function.html#Call-Function). To use a macro it needs to be defined in the same file, before the call.
Limitations:
- A macro is a multiline thing so can't be created using the `compileString` function. A consequence of this is that you can't define macros in YAML (because checkyaml uses `compileString`) to compile inline tables.
To do:
- The documentation needs to be updated.
Credit goes out to Mike Gray who originally came up with the macro idea.
=> Add macro feature

.github/workflows/check-format.yml, configure.ac, liblouis/compileTranslationTable.c, liblouis/internal.h, liblouis/liblouis.h.in, liblouis/logging.c, liblouis/lou_backTranslateString.c, liblouis/lou_translateString.c, tools/lou_checkyaml.c
Change the preferred clang-format to version 9 as that is contained in all versions of Ubuntu since 20.04 (which the CI runner is using) up to Ubuntu 22.04. Seems like a pretty save bet. 
BTW my current dev machine doesn't even have clang-format-7 anymore.
=> Prefer clang-format version 9

contrib/liblouis.el
No longer try to actually parse all the statements. Just highlight
comments, opcodes and prefixes. Also make sure '"' is handled
properly (as plain punctuation), wrapping in comments works correctly.
Lastly there is an attempt to load the mode automatically based on the
magic string "# liblouis: " at the beginning of the file.
=> Simplify liblouis Emacs mode and make it actually usefull.

liblouis/compileTranslationTable.c, liblouis/lou_translateString.c, tests/yaml/numericmode.yaml
Various fixes to the new mode indicators introduced in version 3.20 (https://github.com/liblouis/liblouis/pull/1123):
- Fix regression https://github.com/liblouis/liblouis/issues/1152.
- Fix the problem that @Futyn-Maker had when trying to use the new feature in the Russian table
- Allow implementing numeric mode using the generic mode feature
=> Various fixes to mode indicators

NEWS, liblouis/lou_translateString.c, tests/braille-specs/de-g1-bidi-specs.yaml, tests/yaml/issue-615.yaml
=> Only disable contraction in numeric mode if nocontractsign is actually defined

NEWS, extra/generate-display-names/display-names, tables/Makefile.am, tables/de-comp6.utb, tables/de-de-comp8.ctb, tests/Makefile.am, tests/braille-specs/Makefile.am, tests/braille-specs/de-comp6.yaml, tests/braille-specs/de-de-comp8.yaml, tests/braille-specs/de-eurobrl6.yaml
From the comments in the new table:
```
```
=> Add a German 6-dot computerbraille table

liblouis/lou_translateString.c
It is an undefined behavior to ask for a variable-length-array with size
0. We thus have to avoid it entirely. Just allocating one element is fine
here.
=> Fix zero-length variable-length-array

tests/typeform.c
inlen is initially set as the mere C string length, lou_translate
expects the number of wide characters, which is actually exactly what
_lou_extParseChars returns.
=> typeform test: avoid oversized input buffer size

liblouis/compileTranslationTable.c
This is a fix for issue #1184.
=> prevent processing of characters beyond the string end

tables/en-gb-comp8.ctb
Both + and < symbols have 236 in the same table, which is wrong. The correct for '+' is 235 which is confirmed by this document from UK Association for Accessible Formats in page 24: https://www.ukaaf.org/wp-content/uploads/2020/03/Braille-Computer-Notation-PDF.pdf
As notified by @glenbuck1 on https://github.com/liblouis/liblouis/issues/1087
=> Amend + symbol in en-gb-comp8.ctb

liblouis/compileTranslationTable.c
This is a proposal to fix issue #1171. To prevent writing past the `CharsString` memory block, I replaced all assignments to `passInstructions[passIC++]` with macro `APPEND_INSTRUCTION_CHAR(ch)` that checks the validity of index `passIC` before assigning a value.
The sample file used to trigger the buffer overflow in #1171 only affects `pass_lookback`. But since there are a couple of similar sections that append more than one character without checking the index, I adapted all of them. The "ugly" macro could be replaced by dedicated index checks to reduce the number of `if` statements and to speed up the code a bit, but I decided against that to avoid code bloat.
=> prevent memory overflow in compilePassOpcode

liblouis/metadata.c
Clang 11 on macos will fail to build 3.21.0's `metadata.c` otherwise, complaining:
```
metadata.c:537:13: error: too many arguments provided to function-like macro invocation
sizeof(FeatureWithLineNumber));
^
/nix/store/c5jrszdq2hy3hj9rpyx3hk9gba60wd1d-Libsystem-1238.60.2/include/secure/_string.h:64:9: note: macro 'memcpy' defined here
#define memcpy(dest, src, len)                                  \
^
metadata.c:533:11: note: parentheses are required around macro argument containing braced initializer list
memcpy(malloc(sizeof(FeatureWithLineNumber)),
```
Full build log available at https://hydra.nixos.org/log/jpjrkavb354d98lidivsxv5c8y5li2jc-liblouis-3.21.0.drv
=> analyzeTable: correctly parenthesize src arg of memcpy calls

liblouis/lou_backTranslateString.c
Translation context such as whether the next char is upper case or whether we are inside an all upper case word, etc is currently stored in a number of global variables. This complicates the API of many of the functions.
This PR moves these state variables into a struct and consequently only has to pass this struct around to the functions which simplifies the calling API of said functions quite a bit.
=> Move translation context into a struct

extra/generate-display-names/display-names, tables/Makefile.am, tables/de-g2-detailed.ctb, tables/de-g2.ctb, tests/Makefile.am, tests/braille-specs/Makefile.am, tests/braille-specs/de-g2-detailed-specs.yaml
A German grade 2 table with capitalization and detailed accents. To be able to recommend it for back-translation is an other step (look at the result of the back-translation in the YAML test). It probably needs similar rules just for back-translation as @BueVest  added for `de-g1-detailed.utb`.
Resolves #1212
=> Add a table for German grade 2 with capitalization

tables/de-g0-core.uti, tables/de-g1-core.cti, tables/de-g2-core.cti, tests/braille-specs/de-g0.yaml, tests/braille-specs/de-g1.yaml, tests/braille-specs/de-g2-sbs.yaml, tests/braille-specs/de-g2.yaml
@egli I've started to work on the emphasis issues.
The first issues I'm looking at it the missing dot 6 before the begword marker when it happens inside a word. A lot of failing tests seem to be because of this. My solution involves checking the character before dots 456 (in pass2) and adding dot 6 if it is a letter or a contraction. In order to be able to know whether a dot pattern is a contraction I needed to add a virtual dot. For now I decided to not drop this virtual dot in a later pass and include it in the output. I think this could be useful. The calling application might want to do something special with this extra information. For example, dots 26a will represent the "or" contraction while dots 26 will represent the question mark. The calling application might have a braille …
=> Fix some German emphasis issues

tables/hu-exceptionwords.cti, tables/hu-hu-g1.ctb, tables/hu-hu-g1_braille_input.cti, tables/hu-hu-g2.ctb, tables/hu-hu-g2_exceptions.cti
Hi Chris and Bert,
I ported nonumsign opcode the hungarian tables. Fortunately not need do more works this change related, neeed doed only small changes with hu-hu-g1.ctb and hu-hu-g2.ctb tables and affected subtable files.
The change is full review ready, I will don't commit any change this feature branch. So, this table change related I doed a final push. :-):-)
If fit your time, please do a review and a final merge for the master branch.
The translation quality passed my local large 1857864 words containing test yaml corpus database, so the change hungarian translation tables related not result regression.
Kind regards,
Attila
=> hu-hu-g1.ctb, hu-hu-g2.ctb: implemented hungarian nonumsign rules

tables/ja-kantenji.utb, tests/braille-specs/ja-kantenji.yaml
When converting text which includes e-mails or URLs, lou_translate stops processing. So I removed teh compbrl lines it doesn't apply special substitions for e-mails and URLs and avoid lou_translate stops processing.
=> removed the computer braille indicator part, it's not official Braille Kanji's rule

liblouis/compileTranslationTable.c, tables/hu-hu-g1_braille_input.cti
We can check at compile-time that we always have exactly one startReplace
character followed by one endReplace.
This is needed otherwise when a table misses the endReplace (as
tables/hu-hu-g1_braille_input.cti fixed here), match has
startReplace != -1 but endReplace == -1, and eventually passDoAction
sets newPos to -1, and other functions such as setBefore underflow the
buffer.
=> compileTranslationTable: Check replacement characters []

liblouis/lou_translateString.c
output.length can be larger than input.length, in which case wordBuffer
and emphasisBuffer are not large enough any more, leading to buffer
overflows.
=> _lou_translate: realloc buffers when table needs several passes

NEWS, tables/bel.utb, tables/kk.utb, tables/uk.utb, tests/braille-specs/uk.yaml, tests/yaml/precedence.yaml
Hi!
This PR adds tests for Ukrainian capital letters, because the bug in displaying them has been found.
The problem is that some specific Ukrainian letters are in the Russian braille table, but they have other definitions there (this is for reading Old Church Slavonic texts).
uk.utb:
```
lowercase \x0454 3459    CYRILLIC LETTER IE   є
lowercase \x0456 134569  CYRILLIC LETTER I    і
lowercase \x0457 14569   CYRILLIC LETTER II   ї
...
base uppercase \x0404 \x0454  CYRILLIC LETTER IE   Єє
base uppercase \x0406 \x0456  CYRILLIC LETTER I    Іі
base uppercase \x0407 \x0457  CYRILLIC LETTER II   Її
```
ru-litbrl.ctb:
```
noback lowercase \x0454 159-34-34
noback lowercase \x0456 249-34
noback lowercase \x0457 249-34-34
...
base uppercase \x0404 \x0454
base uppercase \x0406 \x0456
base uppercase …
```
=> Problems in the Ukrainian braille table and priority of `base` rules

AUTHORS, NEWS, tables/en-ueb-g2.ctb, tests/braille-specs/en-ueb-computer-code.yaml
- Handles the case where semicolons could be interpreted as "be" standing alone
- Conservatively places a grade 1 indicator (56) in frost of semicolons, colons, and periods that appear at the beginning of words in grade 2 Braille
- Adjusts initial punctuation tests to expect a Grade 1 indicator in front of colon, semicolon, and period
- Removes xfail on tests than now pass (and fix those than were initially incorrect)
- Introduces new tests
Fixes #1239
=> Fixes UEB grade 2 punctuation being ambiguous with initial groupsigns

NEWS, tables/zh-tw.ctb, tests/braille-specs/zh-tw.yaml
Summary of changes:
* Update the copyright declaration
* Clear a trailing whitespace
* Update braille patterns of some Chinese characters and phrases
* Add braille patterns for various Greek symbols
* Add "Math rules" section and the mixed number rule
* Add braille patterns for ☐ (⣏⣀⣹t, ☑ (⣏⣿⣹), and ☒ (⣏⣭⣹)
Note: The following line
`# Han character testcases (inform the maintainer if any change to this line)`
is meant to be recognized by some script to manage thousands of testcases.
Reviewers:
- 嘯傲俠羽 &lt;<crazy@mail.batol.net>&gt;
- 黃偉豪 &lt;<hurt.nzsmr@gmail.com>&gt;
- 陳鵬安 &lt;<andy72039@gmail.com>&gt;
- T.Y. Lee &lt;<005tylee@gmail.com>&gt;
=> Update zh-tw.ctb to version 2022-08

extra/generate-display-names/Makefile, extra/generate-display-names/go.mod
The generate-display-names script did not work anymore with the latest version of go.
=> Fix metadata check

.github/workflows/fuzzing.yml, .gitignore, configure.ac, liblouis/Makefile.am, tables/Makefile.am, tests/Makefile.am, tests/fuzzing/README.md, tests/fuzzing/build-corpus.py, tests/fuzzing/fuzz_translate.c, tests/fuzzing/minimize-corpus.sh
Hi all,
We are 3 students in IT security ( @annastan, @kmamadoudram, @yocvito) and are currently working on fuzzing liblouis/espeak-ng for a school project with @sthibaul. For liblouis, we have decided to focus on translation/back-translation functions and for now, only the translation fuzzer is available but we will add the back-translation one soon. We come here to show you the work we have done and to try to improve it.
**So, what have we done yet ?**
Basically, we have used _libfuzzer_ to implements fuzzing on `lou_translateString` and `lou_backTranslateString`. The fuzzer just look for an ENV variable containing the table you want to test, avoid liblouis logging and start fuzzing.
If you are already familiar with libfuzzer, then there is no other specific switch than libfuzzer ones …
=> Adding fuzzer for lou_translateString and lou_backTranslateString

AUTHORS, SECURITY.md
Proposal for a very simple security policy. Based on the template from https://github.com/ossf/oss-vulnerability-guide/blob/main/templates/security_policies/github_security_policy.md
=> Add a security policy

NEWS, liblouis/compileTranslationTable.c, liblouis/liblouis.h.in
See https://lwn.net/Articles/507319/ for more background on the security problems of strcpy.
Fixes #1292
=> Check the length of path before copying into dataPath

liblouis/logging.c
=> Check filename before coping to initialLogFileName

liblouis/compileTranslationTable.c
Fix #1291.
Add check for path length before every string-related functions.
=> Check the path length before coping into tableFile

NEWS, tables/nl-comp8.utb, tests/braille-specs/nl-comp8_harness.yaml
This updates the NL Computer braille table (8 dot) to the 2022 standard. I will also file an appropriate braille spec update.
=> NL Comp8 braille 2022 update

NEWS, liblouis/compileTranslationTable.c, liblouis/liblouis.h.in
There are several other ways to set the table search path:
- The recommended and most straightforward way to set the search path is to set the LOUIS_TABLEPATH environment variable.
- You can also set a custom table resolver function through lou_registerTableResolver.
- If you use the metadata based query API and haven't set the LOUIS_TABLEPATH environment variable, you can use the lou_indexTables function to tell Liblouis which files (not directories) to search.
- Finally, there is always the fallback solution of using absolute file paths.
Fixes https://github.com/liblouis/liblouis/issues/1298
=> Deprecate lou_setDataPath and lou_getDataPath

NEWS, tables/sl-si-comp8.ctb
This is quick fix in slovenian table. These 2 chars were missing. More detailed review and rewriting of slovenian tables will follow shortly, when official upgraded slovenian standard will be completed. Anyway I will very appretiate your help. link to valid standard (in slovenian): http://brajica.splet.arnes.si/files/2015/02/Brajica-3.0.pdf
thanks.
=> trying to update the table with character ! and #.

tables/hu-backtranslate-word-corrections.cti, tables/hu-chardefs.cti, tables/hu-exceptionwords.cti
Hi Boys,
I added new forward and backward translation exceptions the hungarian grade1 and grade 2 tables, and updated the testcase file (tests/braille-specs/hu-hu-g1_special_consonants.yaml file).
Changed files:
- tables/hu-exceptionwords.cti, tables/hu-chardefs.cti, tables/hu-backtranslate-word-corrections.cti file: this files containing the new or changed rules.
Typical for example previous Liblouis release already added the lowercase letter beginning word (for back-translation correction), but now during large extended corpus testing detected to need adding uppercase variant a word.
This three files review is easy, but the change affecting only the hungarian language Braille output, other languages unaffected.
- tests/braille-specs/hu-hu-g1_special_consonants.yaml: this file you not …
=> Add newforward and backward exceptions and new testcases in hungarian Braille tables

liblouis/compileTranslationTable.c
`lou_getDataPath` is still used by `_lou_getTablePath` so shouldn't have the deprecation warning.
This partly reverts commit 778aff1e.
=> Don't use lou_getDataPath in _lou_getTablePath

python/README.md
Summary of changes:
* Clarifications about specifics of installation
* Need to compile with 32-bit Unicode for tests to run successfully
* Filename and default directory need to be right for tests
=> Update README for Python bindings

tests/fuzzing/build.sh, tests/fuzzing/fuzz_translate_generic.c
Adds a new fuzzer for oss-fuzz that is a migration of https://github.com/liblouis/liblouis/blob/master/tests/fuzzing/fuzz_translate.c  Modified the build script so OSS-Fuzz automatically picks it up. Down the line we could migrate this and https://github.com/liblouis/liblouis/blob/master/tests/fuzzing/fuzz_translate.c but for now it would be nice to keep them separate as https://github.com/liblouis/liblouis/blob/master/tests/fuzzing/fuzz_translate.c relies on existing table files and it would be nice to avoid those when fuzzing by way of oss-fuzz.
=> Add generic translation fuzzer and make it run on OSS-Fuzz

.github/workflows/check-format.yml, .github/workflows/cifuzz.yml, .github/workflows/emscripten.yml, .github/workflows/macro.yml, .github/workflows/mingw.yml
- such as `emscripten` and `mingw`
=> Reduce CI load

tools/brl_checks.c
This bug was reported in https://github.com/liblouis/liblouis/issues/1346.
=> Fix out-of-bound write in brl_checks.c

tables/da-dk-g16-lit_1993.ctb, tables/da-dk-g16.ctb, tables/da-dk-g16_1993.ctb, tables/da-dk-g26-lit_1993.ctb, tables/da-dk-g26.ctb, tables/da-dk-g26_1993.ctb, tables/da-dk-g26l-lit_1993.ctb, tables/da-dk-g26l_1993.ctb, tables/de-de.dis, tables/kannada.cti, tables/km-g1.utb
The liblouis table parser is quite lenient in what it accepts. Opcodes or comments do not have to start at the beginning of the line. To make parsing easier just drop the few cases where a table doesn't conform to this informal standard:
- make sure all opcodes start at the beginning of the line
- make sure all comments start at the beginning of the line
=> Make sure all opcodes and comments start at the beginning of the line

tables/da-dk-g26-lit_1993.ctb, tables/da-dk-g26.ctb, tables/da-dk-g26_1993.ctb, tables/da-dk-g26l-lit_1993.ctb, tables/da-dk-g26l_1993.ctb, tables/da-dk-g28.ctb, tables/da-dk-g28_1993.ctb, tables/da-dk-g28l_1993.ctb, tests/braille-specs/da-dk_1993.yaml
Changed two contractions in the 2022 grade 2 tables in accordance with updates from the Danish Braille committee.
Removed nocont entries for filenames and domain suffixes from the 1993 tables. This was previously already done in the 2022 tables.
Should be ready to merge.
=> Danish2306

doc/liblouis.texi, tools/lou_translate.c
instead say that the encoding depends on the character definitions and recommend to use a display table.
=> Do not claim that en-us-g2.ctb produces ASCII braille

.gitignore, configure.ac, tests/Makefile.am, tests/fuzzing/Makefile.am, tests/fuzzing/README.md, tests/fuzzing/fuzz_backtranslate.c
@sthibaul @DavidKorczynski I made some changes to the build system and the README in an attempt to clarify the different fuzzers that exist and are run through CI, and make it possible to run them manually to reproduce issues.
Could you please check that I didn't mess anything up?
For example, was it a good idea to enable the 'address' and 'undefined' sanitizers on `--with-fuzzer` in order to be able to reproduce ASAN issues? Or does it have unwanted side effects?
I also tried to compile `fuzz_backtranslate` on `--with-fuzzer` (similar to how I added [fuzz_translate_generic](https://github.com/liblouis/liblouis/commit/9fa56a44bb96201e090663f94adcf17ede374a14)), but that resulted in a build failure. Any idea why? I haven't tried adding `table_fuzzer` yet.
Also note that I had to partly …
=> Fuzzing cleanup

tables/Makefile.am, tables/nl-BE.dis, tables/nl-NL-g0.utb, tables/nl-chardefs.uti, tables/nl-print.dis, tables/nl-unicode.dis, tests/braille-specs/nl-g0_harness.yaml
The idea is to attach virtual dots to the braille output in order to make it possible to distinguish between identical dot patterns that originate from different input. For instance, the braille pattern for digit "1" will have a virtual dot to distinguish it from the letter "a".
The tests illustrate the idea nicely. An excerpt: https://github.com/liblouis/liblouis/blob/f8a1de50845d7ed6096f68e493b906aed4d7ba96/tests/braille-specs/nl-g0_harness.yaml#L610-L615
=> Add virtual dots to Dutch output

tests/braille-specs/no_harness.yaml
When acronyms are mixed capitals and small letters the capital sign should be present in front of each capital like this:
KrFU: ⠠⠅⠗⠠⠋⠠⠥
Not like this:
⠠⠅⠗⠠⠠⠋⠥
This pull request adds a test for this.
=> norwegian: added test for mixed capital and small letters

tables/hu-backtranslate-word-corrections.cti, tables/hu-exceptionwords.cti
Hi Boys,
As it is usual, I added new forward and backward translation exceptions with hungarian language Braille tables, and created or modified required testcase entries the previous autogenerated dictionary file.
The review is very easy:
The first commit diff output is not large, only 393 lines, and affects only with hungarian language related exceptions, other languages is not affected.
The second commit not need detailed reviewing, because contains only the tests/braille-specs/hu-hu-g1_dictionary_special_consonants.yaml testcase file update.
My local test results:
1. All required Liblouis tests passed my local system into the tests directory, other languages is not affecting this update, regression errors will be not happens with other languages if the change is merged into the master …
=> Add new forward and backward translation exceptions and testcases with hungarian Braille tables

.github/workflows/codeql.yml, .github/workflows/fuzzing.yml
- Add a note to `codeql` why it is only run with `schedule`
- Do not run scheduled jobs in forked repos
=> Further reduce CI load

liblouis/compileTranslationTable.c
In liblouis/compileTranslationTable.c file needs do this small modification with issue #266 related.
Original version not presents table names with contains duplicated emphasis flags, for example bold, italic, underline, transnote, etc.
This is a partial fix, because table levels not fixed the duplicate definitions. So, this is only one step forward.
Attila
=> liblouis/compileTranslationTable.c: present table filename with Duplicate emphasis class warning message in check_all_table.pl

tables/hu-backtranslate-word-corrections.cti, tables/hu-exceptionwords.cti
Hi Boys,
I added newest founded forward and backward translation exceptions in tables/hu-exceptionwords.cti, and tables/hu-backtranslate-word-corrections.cti file.
Because the new release scheduled in september 12, if this is possible please add this PR the 3.27 milestone list and merge this change the master branch.
Not have larger changes since previous update, I added only 8 new back-translation exceptions and 20 new forward translation exceptions.
The diff output is absolute not large, review is very easy. The first commit is only 114 lines.
The second commit diff output is only 102 lines, but this commit is not need reviewing, because the second commit contains the readed verifyed new testcase outputs.
Other languages are not affected this change, regression errors will be not …
=> Addew new founded forward and backward translation exceptions and testcases

liblouis/compileTranslationTable.c
Hy Boys,
In issue #266 @bertfrees asked a code modification with liblouis/compileTranslationTable.c file to tests/check_all_tables.pl.log file what tables how many warning message are presents.
The resulted check_all_table.pl.log file is more elegant now, see an example log:
```
/usr/src/liblouis/tables/en-us-emphasis.uti:27: warning: Duplicate emphasis class: italic
/usr/src/liblouis/tables/en-us-emphasis.uti:28: warning: Duplicate emphasis class: underline
/usr/src/liblouis/tables/en-us-emphasis.uti:29: warning: Duplicate emphasis class: bold
/usr/src/liblouis/tables/ko-2006-g2.ctb: 6 warnings issued
/usr/src/liblouis/tables/en-us-emphasis.uti:27: warning: Duplicate emphasis class: italic
/usr/src/liblouis/tables/en-us-emphasis.uti:28: warning: Duplicate emphasis class: underline …
```
=> liblouis/compileTranslationTable.c: check_all_tables.pl.log presents table name and issued warning numbers

tables/en-ueb-g1.ctb, tests/braille-specs/en-ueb-06-numeric_mode.yaml
Resolves #1323 
Fixes an issue when in a capitalized passage, a letter indicator is not inserted for a capital letter following a number (e.g. AB1234FG requires a letter indicator between 4 and F, but is not currently getting one).  This was caused because `numericnocontchars` is case sensitive (see also #631) and the UEB table only included lowercase letters.
=> UEB: Ensure letter indicators are added to letters A-J following numbers in a capitalized passage

tables/hu-backtranslate-word-corrections.cti, tables/hu-exceptionwords.cti
Hi Boys,
As it is usual between releases to releases, I added many new forward and backward translation exceptions with hungarian subtable files related (affected subtable files is tables/hu-exceptionwords.cti and tables/hu-backtranslate-word-corrections.cti file).
Review is easy, the first commit is not very large (only 328 lines), the first commit affects only with only hungarian subtable files.
The second commit contains new added and verifyed exceptions related testcase entries.
This new testcase entries I manual readed in my Braille-display before added the affected test dictionary file.
You not need reviewing the second commit (you dont will be wanting this), because the second commit patch is bigger, 828 lines. :-):-)
This commit affects only the hungarian language test case file, …
=> Added some new forward and backward translation exceptions with hungarian subtable files

Dockerfile.win32, Dockerfile.win64
These docker images are used to build cross-compiled binaries, so they are quite important. So do not frivolously upgrade to the latest Debian. Instead stay with bullseye as (I presume) it was before #1413.
This in part reverts #1413
=> Pin the cross-compile docker images to bullseye

tables/en-ueb-chardefs.uti, tables/en-ueb-g2.ctb
3 last-minute commits for minor improvements to UEB table.
(apologies that GIT thinks there are far more changes)
1. Fix back translation of dots 26 - when standing alone; should be the word enough.
2. Fix assignment for the right double arrow and added left, up, and down double arrows.
3. Fix typos in a couple of rules.
4. This will fix words beginning CONS- and DISHD- when written uppercase.
Many thanks again.
=> Further last-minute UEB improvements

liblouis/lou_translateString.c
Make sure the size param for `memcpy` is not negative.
This should fix https://oss-fuzz.com/testcase-detail/6608976274653184 also mentioned in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60723
For inspiration I looked at https://github.com/inikep/lizard/commit/02491c71c2e6fd5c10997404df2f18d0fc7afadb
=> Fail if the size param to memcpy is negative

tests/Makefile.am, tests/braille-specs/Makefile.am, tests/braille-specs/en-ueb.yaml
As suggested in the discussion at PR #1491, to avoid creating many different test files in response to individual issues, UEB table-related tests will be stored in a single YAML file. Historically this file contained only examples from the UEB rulebook, but this clarifies that the examples are not limited to that source.
(Submitted as a separate PR for clarity as the change has nothing to do with that PR.)
=> Update UEB tests file to clarify that the UEB tests are not limited to rulebook examples

NEWS, tables/bel.utb, tables/ru-litbrl.ctb, tables/uk.utb, tests/braille-specs/bel.yaml, tests/braille-specs/uk.yaml
Hi! Haven't contributed to Liblouis for a while, got some free time! :-)
This commit adds back translation support for Ukrainian and Belarusian literary braille: additional letters that are not in the Russian alphabet can now be translated back.
I'll add a news entry a bit later!
=> Add back translation for Belarusian and Ukrainian literary braille

AUTHORS
Hi Boys,
I have a suggestion that I have been thinking about for a long time:
Since February, Norbert has made very significant improvements to the file of the Liblouis math sub-table, in addition, in the case of the Hungarian language, he developed the Braille display of Greek letters all by himself the proper hungarian subtable (the subtable I already documented he with contributor), and brought the Nemeth Braille tables to the level of the Liblouisutdml project as much as possible. So, in Liblouisutdml level Norbert doed entire the nemeth.ctb and proper edit tables actualization related tasks (co-author), I provide only the technical support to Norbert have possibility only concentrate the table development.
If this is possible, I would like to suggest that you include Norbert in the …
=> Added Norbert Márkus to the AUTHORS file

tables/hu-backtranslate-word-corrections.cti, tables/hu-exceptionwords.cti
Hi guys,
As usual, I made updates and new exceptions for tables/hu-exceptionwords.cti and tables/hu-backtranslate-word-corrections.cti files, and added new test subjects to the Hungarian word database test file.
The first commit contains the list of exceptions, the second commit contains the entries of the test cases. The second commit does not need to be reviewed, the commit contains Hungarian language-specific test cases.
The first commit is not big, approx. 428 lines.
The second commit is long, it contains the test case file modifications, approx. 1528 lines, it is not necessary to subject this to review. :-):-)
The make check command ran successfully on my machine.
The large Hungarian grade1 corpus test did not show any errors, the entire grade1 word database was correctly translated …
=> Added new forward and backward exceptions with hungarian subtables

tests/fuzzing/fuzz_translate_generic.c
To fix a clang-18 error:
```
make[1]: Leaving directory '/src/liblouis'
table_fuzzer.cc:19:16: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
19 |         char *table = "empty.ctb";
|                       ^
1 warning generated.
fuzz_translate_generic.c:86:9: error: call to undeclared function 'unlink'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
86 |         unlink(new_file);
|         ^
fuzz_translate_generic.c:104:9: error: call to undeclared function 'unlink'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
104 |         unlink(new_file);
|         ^
fuzz_translate_generic.c:119:5: error: call to undeclared function 'unlink'; ISO …
```
=> Update fuzz_translate_generic.c: Add missing include unistd.h

tests/yaml/attribute.yaml, tests/yaml/back_cont_then_punc.yaml, tests/yaml/before_begmidword.yaml, tests/yaml/begcaps_endcaps.yaml, tests/yaml/broken_equals_operand.yaml, tests/yaml/capsnocont.yaml, tests/yaml/computer_braille.yaml, tests/yaml/example_test.yaml, tests/yaml/precedence.yaml
Quite a few of the yaml tests in `tests/yaml` do not use display table definitions. Add display table definitions to many of them. This helps with portability with louis-rs.
=> Add display table definitions to many of the yaml tests

tests/braille-specs/lo.yaml
The yaml tests for Lao braille use a plain table (`latinLetterDef6Dots.uti`) in the display table. This is very fishy and naturally fails in louis-rs.
So I converted the yaml test to use a "normal" display table using only display opcodes.
=> Fix the display table for Lao braille yaml tests

python/louis/__init__.py.in, python/tests/test_louis.py
Fix https://github.com/liblouis/liblouis/issues/1551
=> python: use utf_%d_be encoding on bigendian archs

tables/ms-my-g2.ctb, tests/braille-specs/ms-my-g2.yaml
@bertfrees
Hi, sorry. I just realise this mistake when I test the table that you merge to the master from the previous pull request. The word faedah should be word, not always.
About the capital sign, it still can't be shown here.
I think you have add something to these 2 line but I forgot what you add there.
```
noback pass2 [@6@6]@123456 ?
noback pass2 [@6]@123456 ?
```
I think you add the letter "A" but I forgot the correct format. When I play around with that, the capital can be shown. May you help me to re-test that? Thanks.
=> Another Malay Table Correction

tables/es-chardefs.cti, tests/braille-specs/es-g2.yaml
Iván argote Pérez wrote on the mailing list:
> Hello, would you please consider taking ths file to replace the one for Spanish? the line lowdigit has been removed as it did cause punctuation being represented as numbers, as it is in computer English Braille. It is quite complicated for me to open a github ticket, but it won't make any othor side effect change as Spanish table does not have grade 2, thank and best regards.
So I opened a pull request with his changes. I think it sounds reasonable.
=> Remove loweredDigits6dots from Spanish Character Definitions

AUTHORS, tables/fi.utb, tests/braille-specs/fi_harness.yaml
As an answer to issue #1589, here is the updated Finnish 6 dot table for Liblouis.
Overview of changes:
- addition of the Greek alphabet (mostly used in mathematics context)
- added dot patterns for basic arrow characters
- added dot patterns for plus minus and minus plus
- updated the metadata and added the braille authority as a fallback contact
- updated the link to the spec repository (I plan on pull requesting this too with the updated specs).
=> Updated Finnish 6 dot tables

liblouis/compileTranslationTable.c, liblouis/lou_backTranslateString.c, liblouis/lou_translateString.c, tools/brl_checks.c, tools/lou_checkyaml.c
I have created the relevant issues #1530 , #1531 , #1532 , #1533 , #1534 , #1535 , #1536 , #1537 , #1538 , #1539
According to the PoC of those issues, I made initial fixes to these issues. 
Note that in addition to adding some check guards, I tried to make some more core fixes, which modified the original semantics and may break the normal program logic.
The core fixes are listed as follows:
- 00bbd1bfd9ba841e1dd2cef62e455ff030aaa29d : Fix #1532; Make sure `match.endMarch >= 0 && match.endReplace >= 0`
- 6e0248a7f10a9d4caf9552028453c0f3ac3bf437 : Fix #1533; If a bad translation occurs, break the loop and skip some processing.
- 6da6d2754eb61194e668a47f3e0f0c8c79d60bca : Fix #1535; Make `_lou_extParseChars` a pure function, i.e., the same input always results in the same behavior.
- …
=> [fix](lou_checkyaml): fix some memory issues in checkyaml

liblouis/compileTranslationTable.c
The oss-fuzz project discovered some problems with uninitialized values in the various `getTable` functions. See below for a very thorough report. The problems should be fixed with this change.
See also issue 71354 : liblouis: Unintialized pointer in _lou_getTable (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=71354)
> The root cause is that is an unintialized pointer (`newTable`) here: https://github.com/liblouis/liblouis/blob/9741262fb98f6f569d10c27f442d69c71a3abd19/liblouis/compileTranslationTable.c#L5067
```
void EXPORT_CALL
_lou_getTable(const char *tableList, const char *displayTableList,
const TranslationTableHeader **translationTable,
const DisplayTableHeader **displayTable) {
TranslationTableHeader *newTable;
DisplayTableHeader *newDisplayTable = NULL;
getTable(tableList, …
```
=> Initialize table pointers to avoid unintitialized values

python/README.md
It took me a bit of head-scratching, off and on for a couple of days, to get this drill right so I can use PreFigure, which has `liblouis` as a dependency.  Adding this to the `README.md` might save others the trouble?
=> Instructions for installing Python bindings in a virtual environment

tables/es-chardefs.cti, tables/es-g1.ctb, tests/braille-specs/es-g0-g1.yaml
- Removed lowered digits definitely
- Added the noback operator to the apostrophe symbol, since it conflicts with the period, which is used more used.
- Added period and comma as supported characters in numeric mode
=> Updated Spanish grade 1 table

.gitignore, gnulib/Makefile.am, gnulib/m4/gnulib-cache.m4, gnulib/m4/gnulib-comp.m4, gnulib/m4/strcase.m4, gnulib/m4/strings_h.m4, gnulib/strcasecmp.c, gnulib/strings.in.h, gnulib/strncasecmp.c, liblouis/metadata.c
which was used implicitely in `metadata.c`. Now it is used explicitely (using `#include <strings.h>`) and the gnulib module should make sure it also works on windows.
This should fix #1685
=> Add the gnulib module strncasecmp

tables/nl-NL-g0.utb.in, tests/braille-specs/nl-g0_harness.yaml
Thanks @MarcWijnhoven for the bug report.
=> Fix back-translation of capital sign in Dutch

tables/no-no-g0.utb, tests/braille-specs/no.yaml
Got conformation from @larsbjorndal  that the changed URL test was wrong and is now correct.
Fixes https://github.com/liblouis/liblouis/issues/1725
=> Norwegian: don't use permanent cap sign in words with mixed case

liblouis/compileTranslationTable.c
The default table search path didn't match the layout of the pre-compiled Windows packages.
fixes https://github.com/liblouis/liblouis/issues/1701
=> Fix default table search path on Windows

tables/en-ueb-g2.ctb
Originally created by @jrbowden (https://github.com/liblouis/liblouis/pull/1733):
Fix a small number of words containing "somer", e.g. the place "Somerville".
Updated tests to match.
=> Small fix to UEB, words containing "somer"

tables/hu-backtranslate-word-corrections.cti
Hi Boys,
Yesterday I founds few backtranslation exceptions, with fortunatelly only minor important related word back-translation.
Test results is following:
* Other languages affected: no, only hungarian subtable files are accepted.
* Make -j12 check command into the test directory result: passed all Liblouis tests.
* Larger hungarian corpus test: passed.
Since this pull request contains a negligible new word (if I find any new exceptions by tonight, I will add them as fixup commits), please only add this pull request to the 3.33 milestone list if it is possible to approve and merge before the new release on March 3rd.
From tomorrow until March 3rd, I will be doing a complete freeze on Hungarian tables, during which time no new changes will be implemented to make your work easier.
As …
=> tables/hu-backtranslate-word-corrections.cti, tables/hu-exceptionwords.cti: added newest founded few exceptions

liblouis/lou_backTranslateString.c
not when the while loop finishes without having reached the instruction. That it ever reaches this point might be another bug.
See https://github.com/liblouis/liblouis/issues/1719.
=> pass_endTest should only return 1 (match) when "pass_endTest" instruction is reached

tests/braille-specs/nl-g0_harness.yaml
When an emphasized segment is followed by a period (but the period is not emphasized), the emphasis should be ended at the last word, not the second-to-last word.
See https://github.com/liblouis/liblouis/commit/5ebac22a54
=> Add test to cover issue in Dutch g0 table that was fixed by Davy Kager

liblouis/liblouis.h.in, liblouis/lou_translateString.c, tests/yaml/computer_braille.yaml
See https://github.com/liblouis/liblouis/issues/1712
The no_translate typeform bit is undocumented and probably unreliable. Therefore, deprecate it for input. Might use it for output later on, see https://github.com/liblouis/liblouis/issues/1712#issuecomment-2849049632
=> Deprecate no_translate for input

liblouis/metadata.c
I was playing with listDir on Windows and discovered that it did not list files, only dirs. The if check wasn't negated. This should fix that.
=> Fix listDir on Windows to list files instead of dirs

HACKING, README, doc/Makefile.am
We no longer include the html and the txt version of the docs in the distribution tar ball. Instead we explain how the different formats can be built from source in the README and in HACKING
=> Drop prebuilt docs

doc/liblouis.texi
makeinfo (on Mac) seems to have a problem with texinfo nodes that only differ in capitalization
Original PR: https://github.com/liblouis/liblouis/pull/1621
=> Make the lou_checktable node unique

tables/grc-international-common.uti, tests/braille-specs/grc-international-common.yaml
The greek final sigma (ς) will now be backtranslated properly when at the end of a word. Based on rules in hbo provided by @EricJHarvey
=> Support back translation of the Greek final sigma

liblouis/lou_translateString.c
The nocont opcode works by going back to a previous state in the translation process when a certain character sequence is encountered. This was causing an endless loop in some situations involving seqdelimiter.
see https://github.com/liblouis/liblouis/issues/1830#issuecomment-3232756788
=> Fix a bug in the handling of nocont in conjunction with seqdelimiter
