tests/harness/runHarness.py

Support for typeform in harness tests

---

tables/hu-exceptionwords.cti
tests/harness/hu-hu-g1-hyph_harness.txt
tests/harness/hu-hu-g1_harness.txt
tests/harnessSources/hu-hu-g1-hyph_harness_source.txt
tests/harnessSources/hu-hu-g1_harness_source.txt

Please commit this change before the 2.6.2 release creation

hu-exceptionwords.cti: added new exceptions and testcases

---

tables/en-GB-g2.ctb

Names that end thend e.g. Southend

---

tables/hu-exceptionwords.cti
tests/harness/hu-hu-g1_harness.txt

Christian, if you have a little time please merge this modification into the master branch and YAML based feature branch.
The Yaml based harness files I will resolve the difference this testcase related.
I will doing an another pull request the Yaml based harness files related.
Attila

hu-exceptionwords.cti: fixed a typo in a rule

---

tables/hu-exceptionwords.cti
tests/harness/hu-hu-g1_harness.txt
tests/hu-hu-g1_backward.yaml
tests/hu-hu-g1_harness.yaml

Christian, I fixed the sasszámlálás word related expected results the Yaml based harness files.
Please review and merge this modification the proper branch.
Attila

Fix Yaml based harness files the previous wrong expected results

---

liblouis/lou_translateString.c

First pull request. Hope Things Work as expected

Fixed issue 93 (nocross with nocont or compbrl

---

tables/hu-exceptionwords.cti

Hy chris,
Please merge this small modification into Liblouis master branch before the new release creation.
I added only two new exceptions into the hu-exceptionwords.cti table file with not producing any risks the new release creation related.
Attila

hu-exceptionwords.cti: added two new exceptions

---

liblouis/lou_backTranslateString.c
liblouis/lou_translateString.c
liblouis/louis.h
tools/lou_trace.c

i.e. support backtranslation in lou_trace
see also http://www.freelists.org/post/liblouis-liblouisxml/SV-Re-AW-Re-Major-problems-with-german-back-translation-starting-point-needed

lou_trace -b

---

tables/hu-exceptionwords.cti

Hi Chris,
Before new 2.6.6 Liblouis release creation please merge this commit to the Liblouis Github repository proper branch.
With hu-exceptionwords.cti table file I added few new exceptions.
Lou_checktable hu-hu-g1.ctb command doesn't producing any errors, this exceptions is not producing any regressions with hungarian grade1 table.
Attila

Hu.-exceptionwords.cti: added few new exceptions

---

tables/fi.utb
tests/yaml/fi_harness.yaml

Add some common missing symbols to tables.
Add rule for undefined characters.

Finnish symbol additions

---

windows/include/config.h

update config.h to 3.0.0

---

tables/en-ueb-chardefs.uti

Someone who emailed APH noticed this.

Added rules for unicode apostrophe handling.

---

NEWS
tables/Makefile.am
tables/fr-bfu-comp6.utb
tables/fr-bfu-comp68.cti
tables/fr-bfu-comp8.utb

Provided by Michel Such. New include table still uses LGPLv3+.

Updated braille tables for french

---

tests/Makefile.am

Should actually be useful now. This removes about 2000 lines from test-suite.log, which might make it worth merging at this stage.

Cleaned up Danish dictionary tests

---

configure.ac
tools/Makefile.am

Only install lou_checkyaml if libyaml is found

---

tests/Makefile.am
tests/yaml/Makefile.am
tests/yaml/capsword_for_back.yaml

Added yaml test to demo inconsistency in handling of capsword.

---

tools/lou_translate.c

see issue https://github.com/liblouis/liblouis/issues/299

lou_translate: don't print newline if input does not end with newline

---

tables/es-chardefs.cti

A few minor fixes, reviewed and approved by José Luis Lorente Barajas (ONCE-CIDAT).

Bugfix/es g1.ctb

---

liblouis/compileTranslationTable.c

There have been a few CVEs filed against liblouis. These patches fix most of them.

Fix a few invalid writes

---

.gitignore
liblouis/compileTranslationTable.c
liblouis/internal.h
liblouis/utils.c

I believe this fixes CVE-2017-13743 and a number of additional buffer overflows in `_lou_showString`, `_lou_showDots` and `_lou_showAttributes`.

Bugfix for CVE-2017-13743

---

tables/es-chardefs.cti

More fixes proposed by José Luis Lorente Barajas.

Small fixes for es-g1.ctb

---

Dockerfile

see
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

Update the Dockerfile according to best practices

---

tables/zh-tw.ctb

Sorry, the previous PR does not update the version information.

Update zh-tw.ctb version information

---

tables/spaces.ctb

- U+000A LINE FEED (LF)
- U+000B LINE TABULATION
- U+000C FORM FEED (FF)
- U+000D CARRIAGE RETURN (CR)
- U+2028 LINE SEPARATOR
- U+2029 PARAGRAPH SEPARATOR

Added a bunch of whitespace-like codepoints as spaces:

---

tables/fr-2007.ctb
tables/fr-ca-g1.utb
tables/fr-fr-g1.utb

Add missing \x2019 to french tables

---

doc/liblouis.texi

This should solve #415. More to come.

Misc additions and updates to documentation

---

tables/hu-exceptionwords.cti
tables/hu-hu-g1.ctb
tables/hu-hu-g2.ctb
tables/hu-hu-g2_exceptions.cti

Hi Chris,
I doed few modifications with hungarian grade 1 and grade 2 tables.
Before Liblouis 3.4.0 release publication please merge these changes with Liblouis master branch source tree.
The usual lou_checktable hu-hu-g1.ctb and lou_checktable hu-hu-g2.ctb commands passed right without errors.
Attila

Added some new rules with hungarian grade 1 and grade 2 tables

---

liblouis/maketable.c
tests/suggestChunks.c
tests/tables/suggestChunks.ctb
tools/lou_maketable.d/export_chunked_words.py
tools/lou_maketable.d/generate_alphabet.py
tools/lou_maketable.d/lou_maketable.mk
tools/lou_maketable.d/make_suggestions.py
tools/lou_maketable.d/submit_rows.sh
tools/lou_maketable.d/submit_rules.py
tools/lou_maketable.d/submit_rules.sh
tools/lou_maketable.d/utils.py

see issue https://github.com/liblouis/liblouis/issues/455

Maketable fixes

---

tests/yaml/issue-401.yaml

Apparently, order of the two rules involved matters.

Updated test for issue #401

---

doc/liblouis.texi

Solves #402 and #440 + removes some warnings.

More updates to documentationBuevest docs

---

tables/lt.ctb

Nobody wants these escape sequences. :)

Added undefined rule to lt.ctb.

---

tables/fr-bfu-g2.ctb

It is the continuation of #465.

Update French tables

---

doc/liblouis.texi
liblouis/liblouis.h.in
python/louis/__init__.py.in
tools/lou_checkyaml.c

Remove support for comp8Dots

---

NEWS
tables/ur-pk-g1.utb
tables/ur-pk-g2.ctb

Thanks to Jake Kyle
Fixes #516

Add updates to the Urdu tables

---

liblouis/maketable.c
tools/lou_allround.c
tools/lou_translate.c

- `-Wparentheses`
- `-Wdangling-else`
- `-Wsign-compare`
- `-Wpointer-sign`

Fix more warnings

---

tables/Makefile.am
tables/mn-MN-common.cti
tables/mn-MN-g1.utb
tables/mn-MN-g2.ctb
tables/mn-MN.utb
tests/yaml/mn-MN_harness.yaml

Renamed mn-MN.utb to mn-MN-g1.utb. Changed include UEBC.g1.utb to en-ueb-g1.ctb. Changed licencing information

Changed old ueb to new en-ueb-g1.ctb. added few things in  licence information.

---

NEWS
tables/da-dk-g26.ctb
tables/da-dk-g26l.ctb
tables/hyph_brl_da_dk.dic

Updated hyphenation file with a few words.
Corrected back-translation of letters with letsign in 6 dots grade 2.

Minor updates to Danish tables.

---

liblouis/lou_translateString.c
tests/Makefile.am
tests/yaml/Makefile.am
tests/yaml/inpos_outpos.yaml
tests/yaml/issue-537.yaml

This should fix https://github.com/liblouis/liblouis/issues/537.

Fix input-output mapping of context rules

---

doc/liblouis.texi
tests/Makefile.am
tests/yaml/Makefile.am
tests/yaml/issue-412.yaml
tools/brl_checks.c
tools/brl_checks.h
tools/lou_checkyaml.c

Also added support for a new option "maxLength" in YAML tests.

Create a test for issue #412

---

doc/liblouis.texi

Basically just add the comment from the issue and add it as a footnote
to the last paragraph.
Fixes #493

Document output value of inlen

---

NEWS
liblouis/lou_translateString.c
tests/yaml/issue-412.yaml

fixes https://github.com/liblouis/liblouis/issues/412

Fix issue #412: word wrapping not working with all caps words

---

liblouis/compileTranslationTable.c

Reported by Edward-L
Fixes #582

Fix yet another buffer overflow in the braille table parser

---

tests/braille-specs/Makefile.am
tests/braille-specs/zh-tw.yaml

Here is a set of initially selected testcases.
See the following page for some response from other Taiwanese reviewers/users:
<https://groups.io/g/nvda-tw/topic/test_cases_for_zh_tw_ctb/20401735?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,20401735>

Add a YAML test for zh-tw

---

tables/ur-pk-g1.utb
tables/ur-pk-g2.ctb

updated in the light of further proof reading by Urdu braille expert
Fixes #617

Updates to Urdu tables

---

liblouis/lou_backTranslateString.c
liblouis/lou_translateString.c
tests/Makefile.am
tests/braille-specs/en-ueb-09-typeforms.yaml
tests/yaml/Makefile.am
tests/yaml/inpos_outpos.yaml
tests/yaml/issue-583.yaml
tests/yaml/issue-584.yaml
tools/brl_checks.c
tools/lou_checkyaml.c

Fixes issues
- https://github.com/liblouis/liblouis/issues/483
- https://github.com/liblouis/liblouis/issues/583
- https://github.com/liblouis/liblouis/issues/584

Fix input/output positions for back-translation 

---

NEWS
liblouis/compileTranslationTable.c

Remove scripting language pass compiler

---

tables/Lv-Lv-g1.utb
tables/Pl-Pl-g1.utb
tables/Se-Se-g1.utb
tables/pt-pt-g1.utb
tables/sr-chardefs.cti
tests/braille-specs/litdigits6Dots_backward.yaml

The pl, pt, sr and lv tables just needed to add the digits and litdigits. The cs table would need some more work. Who owns the cs tables, and would it be ok to proceed?

Buevest issue490

---

tables/cs-comp8.utb
tables/cs-g1.ctb

Define the undefined char for the Czech tables

---

NEWS
tools/lou_trace.c
tools/lou_translate.c

Moved variables into main(), since they should only be visible from main() and not global.

Add common mode flags to lou_translate and lou_trace

---

AUTHORS
NEWS
tables/Lv-Lv-g1.utb
tests/braille-specs/lv_harness.yaml

Not completely finished yet. Want to clean up my changes to Lv-Lv-g1.utb a bit. But you can already review.

Latvian fixes

---

tables/de-de-comp8.ctb

Fixes #654 
Fixes #388 
Fixes #673

Extend the German 8 dot computer braille table

---

doc/liblouis.texi
liblouis/compileTranslationTable.c
tables/Se-Se-g1.utb
tables/pt-pt-g1.utb

Remove the locale opcode

---

doc/liblouis.texi
extra/generate-display-names/generate.c
liblouis/compileTranslationTable.c
liblouis/liblouis.h.in
liblouis/logging.c
liblouis/lou_backTranslateString.c
liblouis/lou_translateString.c
liblouis/metadata.c
liblouis/utils.c
tests/check_metadata.c
tests/findTable.c
tests/logging.c

Prefix the loglevel enum symbols with LOU_

---

tests/Makefile.am
tests/braille-specs/Makefile.am
tests/braille-specs/no_typeform_harness.yaml

An old branch I had lying around...

Typeform tests for Norwegian

---

liblouis/compileTranslationTable.c

Improve array bounds checking when parsing chars

---

NEWS
doc/liblouis.texi
liblouis/compileTranslationTable.c
liblouis/internal.h
liblouis/lou_translateString.c
tables/nl-chardefs.uti
tables/nl-g0.uti
tests/braille-specs/nl-g0_harness.yaml

Fixed some remaining issues in the Dutch table (commissioned by Transkript, Luisterpuntbibliotheek and Licht and Liefde).
Please have a look, especially @dkager.
If we hurry, we can include this in the 3.10 release :)

Updates to Dutch table

---

NEWS
liblouis/lou_translateString.c
tests/yaml/issue-498.yaml

Fix issue #498

---

NEWS
liblouis/lou_translateString.c
tests/yaml/issue-77.yaml

Fix the hang (loop) mentioned witin issue-77.yaml.

---

NEWS
liblouis/compileTranslationTable.c
tables/ar-ar-g1.utb
tables/ckb-translation.cti
tables/cy-cy-g1.utb
tables/de-g0-core.uti
tables/en-GB-g2.ctb
tables/en-gb-g1.utb
tables/en-in-g1.ctb
tables/en-us-g1.ctb
tables/en-us-mathtext.ctb
tables/ga-g1.utb
tables/grc-international-en.utb
tables/hr-translation.cti
tables/hu-hu-g1.ctb
tables/hu-hu-g2.ctb
tables/kannada.cti
tables/ko-2006.cti
tables/ko-g2-rules.cti
tables/ko.cti
tables/no-no-g0.utb
tables/ru-compbrl.ctb
tables/ru-litbrl.ctb
tables/ru-ru-g1.utb
tables/sk-sk-g1.utb
tables/sk-sk.utb
tables/sl-si-g1.utb

Just opening PR. More to come.

Enable always with one char and swapcc for use with back-translation

---

NEWS
liblouis/lou_translateString.c
tests/yaml/capsnocont.yaml

Just added the test for now. More to come, I hope.

Resolve #802: capsnocont leaking to next word

---

doc/liblouis.texi
tests/yaml/issue-400.yaml

Buevest#631

---

python/louis/__init__.py.in

Python bindings: uses the appropriate encoding to encode/decode paths

---

tools/lou_compare.c

This is to fix the issue : #858

Add missing header to build with uClibc as C Library

---

liblouis/compileTranslationTable.c
liblouis/lou_backTranslateString.c
liblouis/lou_translateString.c
liblouis/maketable.c
tests/yaml/issue-332.yaml
tests/yaml/issue-77.yaml

fixes issue https://github.com/liblouis/liblouis/issues/750

Raise error if a dot pattern can not be displayed

---

tables/IPA-unicode-range.uti
tables/IPA.utb
tables/fr-bfu-comp68.cti

Fixes #810 and other small fixes.

fr-bfu-comp68.cti & IPA-unicode-range.uti: various fixes

---

python/louis/__init__.py.in

Fixes #882

---

liblouis/lou_translateString.c
tests/Makefile.am
tests/yaml/Makefile.am
tests/yaml/issue-886.yaml

Fixes https://github.com/liblouis/liblouis/issues/886

Fix issue 886

---

liblouis/lou_backTranslateString.c
liblouis/lou_translateString.c
tests/yaml/input-length.yaml

fixes https://github.com/liblouis/liblouis/issues/770

Fix bug in returned inlen (back-translation)

---

tables/de-de-comp8.ctb
tests/braille-specs/de-de-comp8.yaml

Fix metadata of German computer braille table

---

NEWS
doc/liblouis.texi
tests/Makefile.am
tests/braille-specs/Makefile.am
tests/braille-specs/de-eurobrl6.yaml
tools/brl_checks.c
tools/brl_checks.h
tools/lou_checkyaml.c

Test display tables with lou_checkyaml

---

Makefile.am

for example add a clean target for them

Make the targets for building windows more idiomatic

---

liblouis/lou_translateString.c
tables/fr-bfu-g2.ctb
tests/braille-specs/fr-bfu-g2.yaml

Fix for issue #881

---

tables/nl-comp8.utb
tests/braille-specs/nl-comp8_harness.yaml

Added additional tests. Still a work in progress
Closes #964

Add more tests for Dutch 8 dot computer braille

---

NEWS
tables/ar-ar-comp8.utb
tables/ar-ar-g1-core.uti
tables/ar-ar-g1.utb
tables/ar-ar-g2.ctb
tables/ar-ar-math.uti
tables/ar.tbl
tests/braille-specs/ar-ar-g1.yaml

Also added references to the [Unified Arabic Braille Project website](https://mip.qa/braille).

Update < and > symbols in the Arabic tables thanks to Ikrami Ahmad

---

tables/en-ueb-g1.ctb
tests/braille-specs/en-ueb-06-numeric_mode.yaml

Fixes https://github.com/liblouis/liblouis/issues/1012
@mehgcap @jrbowden @MikeGray-APH This might interest you guys.

Improve and greatly simplify implementation of UEB numeric space

---

tables/ru-chardefs.cti
tables/ru-compbrl.ctb
tables/ru-letters.dis

Change the license of the tables by Igor B. Poretsky to LGPLv2.1

---

tables/nl-comp8.utb

See also #26, #1028.
Contribution by Babbage dates back to the time that I worked there. No Babbage contributions have been made after I left the organisation.

Change license of Dutch 8 dot computer braille table to LGPL 2.1

---

.github/workflows/emscripten.yml

Building and testing seems to work well. Uploading to the snapshot release worked the first time, but seems to fail now.

Port the emscripten build to gh actions

---

python/examples/translate-html.py

Add a Python example how to translate html

---

liblouis/compileTranslationTable.c
liblouis/lou_translateString.c

Fix some valgrind issues

---

tests/fuzzing/build.sh

This PR provides some needed changes for the OSS-fuzz build script.

Update oss-fuzz build file

---

doc/liblouis.texi

Add documentation for begcomp and endcomp again

---

.github/workflows/main.yml

Fixes https://github.com/liblouis/liblouis/issues/1061

Github workflow to run metadata test

---

NEWS
liblouis/compileTranslationTable.c

fixes https://github.com/liblouis/liblouis/issues/1071

Don't ignore last line if no new line at end of file

---

python/.gitignore
python/Makefile.am
python/README.md
python/tests/test.cti
python/tests/test_louis.py
tests/Makefile.am
tests/yaml/Makefile.am
tests/yaml/face-with-tears-of-joy-ucs4.yaml
tests/yaml/face-with-tears-of-joy.yaml

This PR is basically the tests that are mentioned in #848 as Python unittests and YAML tests.
Both the Python and the YAML tests all fail. I do not understand why. Is there a mistake in them?

Tests from #848

---

NEWS
liblouis/compileTranslationTable.c

What the title says. Simple refactoring.

Eliminate lastToken variable

---

NEWS
tables/no-no-chardefs6.uti
tables/no-no-g0.utb
tables/no-no-latinLetterDef6Dots_diacritics.uti
tests/braille-specs/no_harness.yaml

The patch is discussed with NLB.

Fix/upgrade the Norwegian 6 dots braille table and subtables.

---

NEWS
tables/ar-ar-comp8.utb
tests/braille-specs/ar-ar-comp8.yaml

Arabic computer braille: back-translate 256 to Latin full stop

---

liblouis/compileTranslationTable.c
liblouis/internal.h
tools/lou_trace.c

This commit was included accidentally.

Revert "Store the offset of a rule/character/CharDotsMapping in the struct"

---

tests/braille-specs/de-g2-dictionary.yaml

Some more tests for German translation issues in grade 2

---

doc/liblouis.texi

that a native speaker suggested

Some minor stylistic doc improvements

---

autogen.sh

Fix autogen.sh: find command did not work on macOS

---

NEWS
tables/da-dk-g16-lit.ctb
tables/da-dk-g16.ctb
tables/da-dk-g18.ctb
tables/da-dk-g26-lit.ctb
tables/da-dk-g26.ctb
tables/da-dk-g26l-lit.ctb
tables/da-dk-g26l.ctb
tables/da-dk-g28.ctb
tables/da-dk-g28l.ctb
tests/braille-specs/da-dk-g16-lit.yaml
tests/braille-specs/da-dk-g16.yaml
tests/braille-specs/da-dk-g18.yaml
tests/braille-specs/da-dk-g26-lit.yaml
tests/braille-specs/da-dk-g26.yaml
tests/braille-specs/da-dk-g26l-lit.yaml
tests/braille-specs/da-dk-g26l.yaml
tests/braille-specs/da-dk-g28.yaml
tests/braille-specs/da-dk-g28l.yaml

Fixed emphasis, section sign and and dash between numbers

---

NEWS
tables/de-eurobrl6.dis
tables/de-g0-core.uti
tests/Makefile.am
tests/braille-specs/Makefile.am
tests/braille-specs/de-g0.yaml
tests/braille-specs/de-g2-sbs.yaml

- Ported from [dtbook2sbsform](https://github.com/sbsdev/dtbook2sbsform/tree/master/test_xsl)
- Improve the emphasis handling

Add more tests for German Kurzschrift

---

tests/braille-specs/de-g2-sbs.yaml

The tests are from https://github.com/sbsdev/sbs-braille-tables/blob/master/tests to be .exact
Some tests fail because there are pending patches that need to go upstream.

Added all tests from the sbs-braille-tables except computer braille

---

.github/workflows/emscripten.yml
.github/workflows/scripts/emscripten-build.sh

- [Make the emscriptem workflow succeed again](https://github.com/liblouis/liblouis/pull/1205/commits/8d2ee48a61daa7d309d2842cf24752960e4f6973)
- [Don't build build-no-tables-utf16.js because we don't publish it](https://github.com/liblouis/liblouis/pull/1205/commits/326d58b9d676c96f2df026ec129c5c42749120a0)
- [Publish the JS files and the tables to the js-build repository](https://github.com/liblouis/liblouis/pull/1205/commits/8c398ac1295fe0a263597cee755e1b4155824456)

Enable emscriptem workflow

---

liblouis/compileTranslationTable.c

Thanks to Han Zheng for reporting it
Fixes #1214

Prevent an invalid memory writes in compileRule

---

liblouis/lou_translateString.c

Prevent endless loop in doCompbrl

---

NEWS
tables/hu-backtranslate-word-corrections.cti
tables/hu-exceptionwords.cti

Hi Chris and Bert,
First, excuse me the later pull request opening date, previous I have more works (I known, now have august 27TH, and have only eight days before final release date).
I added few critical importanter exceptions with affects both forward and backward translations, and extended the tests/braille-specs/hu-hu-g1_special_consonants.yaml testcase file with importanter new testcases.
If fit the review time, please add this pull request to the 3.23 milestone and review the first commit.
Second commit containing only the testcase file related changes, perhaps not require detailed reviewing.
The changes not producing regression errors with other language, and rans 100% percent good result the 2035273 big hungarian grade 1 forward and backward bothDirections mode local big test …

Improve forward and backward translations with new exceptions and new testcases

---

tables/hu-backtranslate-word-corrections.cti
tables/hu-exceptionwords.cti

Hi Chris or Bert,
If fit the time before 3.23 release prep, and not have more works for example new swedish table update related, please review and approve this small squashed commit. I already doing the commit squashing my feature branch.
I added few new founded translation related exceptions since previous merged pull request.
Not too lot of new exceptions I founded, I think eight or ten new exceptions. :-):-)
The yaml test file related change part not need reviewing detailed.
Of course, the local large test corpus passed right, other test result shows too right results.
If perhaps now have you more works, and not fit now the approve before release prep, not matter if we schedule this pull request the 3.24 future release milestone.
Thank you the cooperation,
Attila

Add few backtranslations exceptions

---

doc/liblouis.texi

Buevest #1182

---

.github/workflows/check-format.yml
configure.ac
liblouis/lou_backTranslateString.c
liblouis/lou_translateString.c
liblouis/pattern.c

14 is the latest version of clang-format that is included in Ubuntu 22.04 which is a Long term Release.

Move to clang-format-14 for code formatting

---

liblouis/lou_translateString.c

This fixes commit 44540d2.
Fixes #1259.

Fix wrong pointer to integer conversions

---

extra/generate-display-names/Makefile
extra/generate-display-names/go.mod
extra/generate-display-names/go.sum

See https://github.com/liblouis/liblouis/pull/1270

Fix metadata check

---

.github/workflows/scorecards.yml

I just followed the instructions in https://github.com/ossf/scorecard-action#installation.
The check isn't run yet. We'll only see it in action when the PR is merged.

Install Scorecard Github workflow

---

.github/dependabot.yml
.github/workflows/check-format.yml
.github/workflows/check-table-license.yml
.github/workflows/cifuzz.yml
.github/workflows/emscripten.yml
.github/workflows/fuzzing.yml
.github/workflows/macro.yml
.github/workflows/main.yml
.github/workflows/metadata.yml
.github/workflows/mingw.yml
.github/workflows/sanitizer.yml
README

- Pin all dependencies of the gh actions by hash (with the help of the  [stepsecurity](https://app.stepsecurity.io/) tool)
-  Set the token permissions to read
-  Add a dependency update tool
-  Add a scorecard badge

Address issues from the scorecard report

---

liblouis/lou_translateString.c

Fixes https://github.com/liblouis/liblouis/issues/1256 and https://github.com/liblouis/liblouis/issues/1231.

Fix bug in doCompbrl()

---

python/louis/__init__.py.in

Details on #1331, which this will close.
I did not rebuild and test this, but the identical edit removes the error that results otherwise.

Finish removing support for Python 2

---

liblouis/compileTranslationTable.c

Clear display table cache on lou_free()

---

tests/fuzzing/build.sh
tests/fuzzing/fuzz_backtranslate.c

The main point of this is to cover the logic in lou_backTranslateString.c.

tests: fuzzing: add fuzzer for backTranslate logic

---

.github/workflows/cifuzz.yml
SECURITY.md

Added a note to SECURITY.md and cifuzz.yml that issues related to table loading are not critical.

Add a note that table loading fuzzing issues are not critical

---

tests/braille-specs/en-ueb-02-stand_alone.yaml
tests/braille-specs/en-ueb-03-symbols.yaml
tests/braille-specs/en-ueb-05-grade_1_mode.yaml
tests/braille-specs/en-ueb-06-numeric_mode.yaml
tests/braille-specs/en-ueb-08-capitalization.yaml
tests/braille-specs/en-ueb-09-typeforms.yaml
tests/braille-specs/en-ueb-10-07-contractions.yaml
tests/braille-specs/en-ueb-10-13-contractions.yaml
tests/braille-specs/en-ueb-computer-code.yaml
tests/braille-specs/en-ueb-g2_backward_no_dis.yaml
tests/braille-specs/en-ueb-math.yaml
tests/braille-specs/en-ueb-repeated-underscores.yaml

Use text_nabcc.dis as display table for UEB tests that had no display table yet

---

Dockerfile

Make the Dockerfile work with the latest Debian

---

liblouis/lou_backTranslateString.c

It didn't look like the issue author was going to return to fix this,
so I took the liberty.
Fixes #1402

Removed redundant if statement.

---

tables/en-ueb-chardefs.uti
tables/en-ueb-g1.ctb
tables/en-ueb-g2.ctb

Fixes https://github.com/liblouis/liblouis/issues/1394

Update maintainer metadata of UEB tables

---

tables/da-dk-6miscChars.cti
tables/da-dk-6miscChars_1993.cti
tables/da-dk-8miscChars.cti
tables/da-dk-8miscChars_1993.cti
tables/da-dk-g08.ctb
tables/da-dk-g08_1993.ctb
tables/da-dk-g16-lit_1993.ctb
tables/da-dk-g16.ctb
tables/da-dk-g16_1993.ctb
tables/da-dk-g18.ctb
tables/da-dk-g18_1993.ctb
tables/da-dk-g26-lit_1993.ctb
tables/da-dk-g26.ctb
tables/da-dk-g26_1993.ctb
tables/da-dk-g26l-lit_1993.ctb
tables/da-dk-g26l_1993.ctb
tables/da-dk-g28.ctb
tables/da-dk-g28_1993.ctb
tables/da-dk-g28l_1993.ctb
tables/da-dk-octobraille.dis
tables/da-dk-octobraille_1993.dis
tests/braille-specs/da-dk-6dot.yaml
tests/braille-specs/da-dk-8dot.yaml
tests/braille-specs/da-dk_1993.yaml

Just a small bug fix. Should be ready for merge.

Fixed a bug when back-translating a word contraction followed by "!"

---

liblouis/metadata.c

Fix the argument type to formatting function

---

liblouis/lou_translateString.c
tests/braille-specs/en-ueb-rueb.yaml

See https://github.com/liblouis/liblouis/issues/1465

Work I did so far regarding the "emphasis phrase with bounding punctuation" issue (#1465)

---

tables/nl-BE.dis
tables/nl-NL-g0.utb
tables/nl-print.dis
tables/nl-unicode.dis
tests/braille-specs/nl-g0_harness.yaml

nl-g0: Do not filter out Unicode braille dot 6

---

NEWS
tables/en-ueb-g2.ctb
tests/braille-specs/en-ueb.yaml

UEB G2: Fix improper use of final letter groupsigns following capital-related indicators

---

liblouis/compileTranslationTable.c

Change redundant emphasis classes from warning to debug

---

tables/devanagari.cti

Please let me know if it was not a spelling mistake and was intentionally wrote like that.

Corrected spelling of Devanagari in its table

---

tools/lou_translate.c

I have created the relevant issue #1540, 
and since this fix does not require me to have a deep understanding of the project, I have tentatively submitted this PR.

[fix](lou_translate.c): fix issue #1540

---

liblouis/metadata.c

- Default value in tables is ucs2
- Default value in queries is determined by CHARSIZE
- ucs2 in table also matches ucs4 in query
see https://github.com/liblouis/liblouis/issues/1521

Special handling of the new `#+unicode-range` metadata field

---

tables/hu-backtranslate-word-corrections.cti
tables/hu-exceptionwords.cti

Hi Boys,
As it is usual, near with 3.30 Liblouis june version publication time, I opening the standard pull request with hungarian braille subtable files extending related.
I added new collected forward and backward translation exceptions with tables/hu-exceptionwords.cti and tables/hu-backtranslate-word-corrections.cti file, and extending the proper testcase file.
I ran the new changes with hungarian large corpus database test file, not have regressions fortunately.
make -j8 check command the tests directory ran successful too.
If this is possible, please put this PR the 3.30 milestone list, and before Liblouis 3.30 version publication please merge this PR to the master branch.
Because Liblouis 3.30 version release date if I remember right is very near, with june 3, after may 25 TH I …

hu-exceptionwords.cti, hu-backtranslate-word-corrections.cti: added new collected forward and backward translation exceptions

---

tables/hu-backtranslate-word-corrections.cti
tables/hu-exceptionwords.cti
tables/hu-hu-g1_braille_input.cti

Hi Boys,
As is it is usual, I added newest exceptions with hungarian tables/hu-backtranslate-word-corrections.cti and tables/hu-exceptionwords.cti subtable files, and added new testcases the test dictionary file.
I doed the large corpus test with large hungarian test dictionary corpus database, estimated 10 million words passed the test, both forward and backward translation tests.
My local machine all Liblouis tests ran successfull with the test directory the make -j8 command.
The first commit contains the exceptions related commit, the second commit contains the testcase file update related commit.
This PR affects only the hungarian language, other tables and subtables are not affected, not have regression risks with delaying the Liblouis 3.31 september 2 determined release date.
If …

tables/hu-backtranslate-word-corrections.cti, tables/hu-exceptionwords.cti: added newest exceptions

---

tables/nl-print.dis

This dot pattern is part of the escape sequence inserted for unknown characters.

Add 12567 to nl-print.dis

---

tables/hu-backtranslate-word-corrections.cti
tables/hu-exceptionwords.cti

Hi Boys,
I opening now this PR with draft marked state, because me need yet proof reading 9000 new words from the updated word database from various sources (books, news portals, wikipedia entries, etc).
In evening, after I doed the last hungarian corpus test, I will remove the draft flag this PR and really doing a hard freeze with hungarian table files. :-):-)
Every day possible founding new exceptions, but very near the release date. So, after friday evening if I get new exceptions from hungarian users, I queuing this requests and collecting these required changes a new list, but beginning will be update table exception files only after september 2, when Liblouis 3.31 version are comed out. So, the hard freeze are lifted out after Liblouis 3.31 release comed out from hungarian table …

tables/hu-backtranslate-word-corrections.cti, tables/hu-exceptionwords.cti: added newest collected and founded exceptions and testcases

---

tables/hu-backtranslate-word-corrections.cti
tables/hu-exceptionwords.cti

Hi Chris and Bert,
As it is usual, I added new forward and backward translation exceptions the tables/hu-exceptionwords.cti, and tables/hu-backtranslate-word-corrections.cti subtable files.
Review is very easy:
The first commit contains the newest exceptions, the second commit contains the new testcase entries.
The first commit related diff patch is only 205 lines, the second commit diff output is longer, but you not would like detailed reviewing the second longer commit, because contains only hungarian language testcase word outputs the affected yaml file related. :-):-)
Please add this PR the 3.32 milestone, please approve and merge this change to the master branch before the release publication.
Test results:
* Regression risks not have this PR related, because this pull request …

tables/hu-backtranslate-word-corrections.cti, tables/hu-exceptions.cti: added new forward and backward translation exceptions

---

tables/Makefile.am
tables/critical-apparatus.uti
tests/braille-specs/critical-apparatus.yaml

This PR provides support for critical apparatus. This commit contains table for the symbols in Critical Apparatus and its relevant yaml.

Created support for Criticle Apparatus

---

doc/liblouis.texi
tools/lou_translate.c

Fixes #1489
Not sure if this needs any documentation. The tools have man pages which are generated automatically based on the help string (which has been enhanced)

Add an option to lou_translate to specify the display table

---

doc/liblouis.texi
liblouis/metadata.c
tools/lou_translate.c

Fixes https://github.com/liblouis/liblouis/issues/1670
@egli I think this should cover everything. We don't need to include this in the release, but it was really not much work so I  did it.

Make value in table metadata field mandatory

---

liblouis/metadata.c

Fix #1708 
Fix #1709 
Fix #1718

Fix free error in parseQuery and analyzeTable

---

liblouis/compileTranslationTable.c

Return from finalizeCharacter if a recursive invocation failed

---

doc/liblouis.texi

This PR add a https protocol text

Fix incorrect links

---

configure.ac
gnulib/Makefile.am
liblouis/Makefile.am
tools/Makefile.am
tools/gnulib/Makefile.am

I found this did the same for Liblouis: https://gist.github.com/andrewgrant/477c7037b1fc0dd7275109d3f2254ea9

Add --enable-macos-universal-binary configuration option

---

tables/Makefile.am
tables/nl-NL-g0.utb.in
tables/nl-chardefs.uti.in
tables/quotation-marks.uti
tests/braille-specs/nl-g0_harness.yaml

see https://github.com/daisy/pipeline-modules/issues/126

Bug in Dutch table: an apostrophe after a number is not always a minute sign

---

liblouis/compileTranslationTable.c
liblouis/internal.h
liblouis/metadata.c

My attempt at fixing https://github.com/liblouis/liblouis/issues/1711. @egli Does it make sense?

Free tableIndex in lou_free
